// Package apitypes provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apitypes

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AttributeDataType.
const (
	Bool      AttributeDataType = "bool"
	Enum      AttributeDataType = "enum"
	MultiEnum AttributeDataType = "multi_enum"
	Number    AttributeDataType = "number"
	Text      AttributeDataType = "text"
)

// Valid indicates whether the value is a known member of the AttributeDataType enum.
func (e AttributeDataType) Valid() bool {
	switch e {
	case Bool:
		return true
	case Enum:
		return true
	case MultiEnum:
		return true
	case Number:
		return true
	case Text:
		return true
	default:
		return false
	}
}

// Defines values for AttributeScope.
const (
	AttributeScopeBooking  AttributeScope = "booking"
	AttributeScopeProvider AttributeScope = "provider"
	AttributeScopeService  AttributeScope = "service"
)

// Valid indicates whether the value is a known member of the AttributeScope enum.
func (e AttributeScope) Valid() bool {
	switch e {
	case AttributeScopeBooking:
		return true
	case AttributeScopeProvider:
		return true
	case AttributeScopeService:
		return true
	default:
		return false
	}
}

// Defines values for BookingCancelledBy.
const (
	BookingCancelledByCustomer BookingCancelledBy = "customer"
	BookingCancelledByProvider BookingCancelledBy = "provider"
)

// Valid indicates whether the value is a known member of the BookingCancelledBy enum.
func (e BookingCancelledBy) Valid() bool {
	switch e {
	case BookingCancelledByCustomer:
		return true
	case BookingCancelledByProvider:
		return true
	default:
		return false
	}
}

// Defines values for BookingMode.
const (
	Instant BookingMode = "instant"
	Request BookingMode = "request"
)

// Valid indicates whether the value is a known member of the BookingMode enum.
func (e BookingMode) Valid() bool {
	switch e {
	case Instant:
		return true
	case Request:
		return true
	default:
		return false
	}
}

// Defines values for BookingStatus.
const (
	BookingStatusCancelledByCustomer BookingStatus = "cancelled_by_customer"
	BookingStatusCancelledByProvider BookingStatus = "cancelled_by_provider"
	BookingStatusCompleted           BookingStatus = "completed"
	BookingStatusConfirmed           BookingStatus = "confirmed"
	BookingStatusInProgress          BookingStatus = "in_progress"
	BookingStatusNoShow              BookingStatus = "no_show"
	BookingStatusPending             BookingStatus = "pending"
)

// Valid indicates whether the value is a known member of the BookingStatus enum.
func (e BookingStatus) Valid() bool {
	switch e {
	case BookingStatusCancelledByCustomer:
		return true
	case BookingStatusCancelledByProvider:
		return true
	case BookingStatusCompleted:
		return true
	case BookingStatusConfirmed:
		return true
	case BookingStatusInProgress:
		return true
	case BookingStatusNoShow:
		return true
	case BookingStatusPending:
		return true
	default:
		return false
	}
}

// Defines values for CreateOptionGroupRequestSelectionType.
const (
	CreateOptionGroupRequestSelectionTypeMulti  CreateOptionGroupRequestSelectionType = "multi"
	CreateOptionGroupRequestSelectionTypeSingle CreateOptionGroupRequestSelectionType = "single"
)

// Valid indicates whether the value is a known member of the CreateOptionGroupRequestSelectionType enum.
func (e CreateOptionGroupRequestSelectionType) Valid() bool {
	switch e {
	case CreateOptionGroupRequestSelectionTypeMulti:
		return true
	case CreateOptionGroupRequestSelectionTypeSingle:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	CONFLICT           ErrorCode = "CONFLICT"
	EMAILTAKEN         ErrorCode = "EMAIL_TAKEN"
	FORBIDDEN          ErrorCode = "FORBIDDEN"
	INTERNALERROR      ErrorCode = "INTERNAL_ERROR"
	INVALIDCREDENTIALS ErrorCode = "INVALID_CREDENTIALS"
	INVALIDTOKEN       ErrorCode = "INVALID_TOKEN"
	INVALIDTRANSITION  ErrorCode = "INVALID_TRANSITION"
	NOTAMEMBER         ErrorCode = "NOT_A_MEMBER"
	NOTFOUND           ErrorCode = "NOT_FOUND"
	ORGREQUIRED        ErrorCode = "ORG_REQUIRED"
	OUTSIDEHOURS       ErrorCode = "OUTSIDE_HOURS"
	PROVIDERINACTIVE   ErrorCode = "PROVIDER_INACTIVE"
	SERVICEINACTIVE    ErrorCode = "SERVICE_INACTIVE"
	SLOTTAKEN          ErrorCode = "SLOT_TAKEN"
	TOKENEXPIRED       ErrorCode = "TOKEN_EXPIRED"
	UNAUTHENTICATED    ErrorCode = "UNAUTHENTICATED"
	VALIDATIONERROR    ErrorCode = "VALIDATION_ERROR"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case CONFLICT:
		return true
	case EMAILTAKEN:
		return true
	case FORBIDDEN:
		return true
	case INTERNALERROR:
		return true
	case INVALIDCREDENTIALS:
		return true
	case INVALIDTOKEN:
		return true
	case INVALIDTRANSITION:
		return true
	case NOTAMEMBER:
		return true
	case NOTFOUND:
		return true
	case ORGREQUIRED:
		return true
	case OUTSIDEHOURS:
		return true
	case PROVIDERINACTIVE:
		return true
	case SERVICEINACTIVE:
		return true
	case SLOTTAKEN:
		return true
	case TOKENEXPIRED:
		return true
	case UNAUTHENTICATED:
		return true
	case VALIDATIONERROR:
		return true
	default:
		return false
	}
}

// Defines values for MemberRole.
const (
	MemberRoleAdmin MemberRole = "admin"
	MemberRoleOwner MemberRole = "owner"
	MemberRoleStaff MemberRole = "staff"
)

// Valid indicates whether the value is a known member of the MemberRole enum.
func (e MemberRole) Valid() bool {
	switch e {
	case MemberRoleAdmin:
		return true
	case MemberRoleOwner:
		return true
	case MemberRoleStaff:
		return true
	default:
		return false
	}
}

// Defines values for OptionGroupSelectionType.
const (
	OptionGroupSelectionTypeMulti  OptionGroupSelectionType = "multi"
	OptionGroupSelectionTypeSingle OptionGroupSelectionType = "single"
)

// Valid indicates whether the value is a known member of the OptionGroupSelectionType enum.
func (e OptionGroupSelectionType) Valid() bool {
	switch e {
	case OptionGroupSelectionTypeMulti:
		return true
	case OptionGroupSelectionTypeSingle:
		return true
	default:
		return false
	}
}

// Defines values for ProviderStatus.
const (
	ProviderStatusActive    ProviderStatus = "active"
	ProviderStatusPending   ProviderStatus = "pending"
	ProviderStatusSuspended ProviderStatus = "suspended"
)

// Valid indicates whether the value is a known member of the ProviderStatus enum.
func (e ProviderStatus) Valid() bool {
	switch e {
	case ProviderStatusActive:
		return true
	case ProviderStatusPending:
		return true
	case ProviderStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for SignInRequestClientType.
const (
	SignInRequestClientTypeMobile SignInRequestClientType = "mobile"
	SignInRequestClientTypeWeb    SignInRequestClientType = "web"
)

// Valid indicates whether the value is a known member of the SignInRequestClientType enum.
func (e SignInRequestClientType) Valid() bool {
	switch e {
	case SignInRequestClientTypeMobile:
		return true
	case SignInRequestClientTypeWeb:
		return true
	default:
		return false
	}
}

// Defines values for SignUpRequestClientType.
const (
	SignUpRequestClientTypeMobile SignUpRequestClientType = "mobile"
	SignUpRequestClientTypeWeb    SignUpRequestClientType = "web"
)

// Valid indicates whether the value is a known member of the SignUpRequestClientType enum.
func (e SignUpRequestClientType) Valid() bool {
	switch e {
	case SignUpRequestClientTypeMobile:
		return true
	case SignUpRequestClientTypeWeb:
		return true
	default:
		return false
	}
}

// Defines values for TokensTokenType.
const (
	Bearer TokensTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokensTokenType enum.
func (e TokensTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// Defines values for UserPlatformRole.
const (
	UserPlatformRoleAdmin UserPlatformRole = "admin"
	UserPlatformRoleUser  UserPlatformRole = "user"
)

// Valid indicates whether the value is a known member of the UserPlatformRole enum.
func (e UserPlatformRole) Valid() bool {
	switch e {
	case UserPlatformRoleAdmin:
		return true
	case UserPlatformRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for PostApiV1OrgMembersJSONBodyRole.
const (
	PostApiV1OrgMembersJSONBodyRoleAdmin PostApiV1OrgMembersJSONBodyRole = "admin"
	PostApiV1OrgMembersJSONBodyRoleStaff PostApiV1OrgMembersJSONBodyRole = "staff"
)

// Valid indicates whether the value is a known member of the PostApiV1OrgMembersJSONBodyRole enum.
func (e PostApiV1OrgMembersJSONBodyRole) Valid() bool {
	switch e {
	case PostApiV1OrgMembersJSONBodyRoleAdmin:
		return true
	case PostApiV1OrgMembersJSONBodyRoleStaff:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1OrgServicesParamsIsActive.
const (
	False GetApiV1OrgServicesParamsIsActive = "false"
	True  GetApiV1OrgServicesParamsIsActive = "true"
)

// Valid indicates whether the value is a known member of the GetApiV1OrgServicesParamsIsActive enum.
func (e GetApiV1OrgServicesParamsIsActive) Valid() bool {
	switch e {
	case False:
		return true
	case True:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1OrgServicesParamsSort.
const (
	GetApiV1OrgServicesParamsSortCategory      GetApiV1OrgServicesParamsSort = "category"
	GetApiV1OrgServicesParamsSortCreated       GetApiV1OrgServicesParamsSort = "created"
	GetApiV1OrgServicesParamsSortDuration      GetApiV1OrgServicesParamsSort = "duration"
	GetApiV1OrgServicesParamsSortMinusCategory GetApiV1OrgServicesParamsSort = "-category"
	GetApiV1OrgServicesParamsSortMinusCreated  GetApiV1OrgServicesParamsSort = "-created"
	GetApiV1OrgServicesParamsSortMinusDuration GetApiV1OrgServicesParamsSort = "-duration"
	GetApiV1OrgServicesParamsSortMinusName     GetApiV1OrgServicesParamsSort = "-name"
	GetApiV1OrgServicesParamsSortMinusPrice    GetApiV1OrgServicesParamsSort = "-price"
	GetApiV1OrgServicesParamsSortName          GetApiV1OrgServicesParamsSort = "name"
	GetApiV1OrgServicesParamsSortPrice         GetApiV1OrgServicesParamsSort = "price"
)

// Valid indicates whether the value is a known member of the GetApiV1OrgServicesParamsSort enum.
func (e GetApiV1OrgServicesParamsSort) Valid() bool {
	switch e {
	case GetApiV1OrgServicesParamsSortCategory:
		return true
	case GetApiV1OrgServicesParamsSortCreated:
		return true
	case GetApiV1OrgServicesParamsSortDuration:
		return true
	case GetApiV1OrgServicesParamsSortMinusCategory:
		return true
	case GetApiV1OrgServicesParamsSortMinusCreated:
		return true
	case GetApiV1OrgServicesParamsSortMinusDuration:
		return true
	case GetApiV1OrgServicesParamsSortMinusName:
		return true
	case GetApiV1OrgServicesParamsSortMinusPrice:
		return true
	case GetApiV1OrgServicesParamsSortName:
		return true
	case GetApiV1OrgServicesParamsSortPrice:
		return true
	default:
		return false
	}
}

// Defines values for GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo.
const (
	GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesToBooking  GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo = "booking"
	GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesToProvider GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo = "provider"
	GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesToService  GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo = "service"
)

// Valid indicates whether the value is a known member of the GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo enum.
func (e GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo) Valid() bool {
	switch e {
	case GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesToBooking:
		return true
	case GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesToProvider:
		return true
	case GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesToService:
		return true
	default:
		return false
	}
}

// AdminBooking The flat cross-tenant triage view.
type AdminBooking struct {
	Code            *string             `json:"code,omitempty"`
	CreatedAt       *time.Time          `json:"createdAt,omitempty"`
	Currency        *string             `json:"currency,omitempty"`
	CustomerEmail   *string             `json:"customerEmail,omitempty"`
	CustomerName    *string             `json:"customerName,omitempty"`
	DurationMinutes *int                `json:"durationMinutes,omitempty"`
	EndsAt          *time.Time          `json:"endsAt,omitempty"`
	Id              *openapi_types.UUID `json:"id,omitempty"`
	PriceCents      *int                `json:"priceCents,omitempty"`
	ProviderId      *openapi_types.UUID `json:"providerId,omitempty"`
	ProviderName    *string             `json:"providerName,omitempty"`
	ProviderSlug    *string             `json:"providerSlug,omitempty"`
	ServiceName     *string             `json:"serviceName,omitempty"`
	StartsAt        *time.Time          `json:"startsAt,omitempty"`
	Status          *BookingStatus      `json:"status,omitempty"`
}

// Attribute defines model for Attribute.
type Attribute struct {
	// AppliesTo What the field describes. `service` fields are set by the provider on a
	// service; `booking` fields are asked of the customer at reservation time.
	AppliesTo  AttributeScope     `json:"appliesTo"`
	CategoryId openapi_types.UUID `json:"categoryId"`
	DataType   AttributeDataType  `json:"dataType"`

	// Filterable Whether discovery may build a filter from it.
	Filterable *bool              `json:"filterable,omitempty"`
	Id         openapi_types.UUID `json:"id"`

	// Key Stable machine name, e.g. `vehicle_size`.
	Key   string `json:"key"`
	Label string `json:"label"`

	// Options Allowed values for `enum` and `multi_enum`.
	Options   *[]string `json:"options,omitempty"`
	Required  bool      `json:"required"`
	SortOrder *int      `json:"sortOrder,omitempty"`
}

// AttributeDataType defines model for AttributeDataType.
type AttributeDataType string

// AttributeScope What the field describes. `service` fields are set by the provider on a
// service; `booking` fields are asked of the customer at reservation time.
type AttributeScope string

// BookedOption A snapshot of the add-on as it was when reserved.
type BookedOption struct {
	DurationDeltaMinutes *int                `json:"durationDeltaMinutes,omitempty"`
	Name                 *string             `json:"name,omitempty"`
	OptionId             *openapi_types.UUID `json:"optionId,omitempty"`
	PriceDeltaCents      *int                `json:"priceDeltaCents,omitempty"`
}

// Booking defines model for Booking.
type Booking struct {
	Attributes   *map[string]interface{} `json:"attributes,omitempty"`
	CancelReason *string                 `json:"cancelReason,omitempty"`
	CancelledBy  *BookingCancelledBy     `json:"cancelledBy,omitempty"`

	// Code Short human reference.
	//
	// Example: BK-7QK2
	Code      string     `json:"code"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	Currency  string     `json:"currency"`

	// CustomerId Null for a walk-in entered by staff.
	CustomerId      *openapi_types.UUID `json:"customerId,omitempty"`
	CustomerName    *string             `json:"customerName,omitempty"`
	CustomerNote    *string             `json:"customerNote,omitempty"`
	CustomerPhone   *string             `json:"customerPhone,omitempty"`
	DurationMinutes int                 `json:"durationMinutes"`

	// EndsAt Includes the service's buffer.
	EndsAt       time.Time           `json:"endsAt"`
	Id           openapi_types.UUID  `json:"id"`
	Options      *[]BookedOption     `json:"options,omitempty"`
	PriceCents   int                 `json:"priceCents"`
	Provider     *ProviderSummary    `json:"provider,omitempty"`
	ProviderId   openapi_types.UUID  `json:"providerId"`
	ResourceId   openapi_types.UUID  `json:"resourceId"`
	ResourceName *string             `json:"resourceName,omitempty"`
	ServiceId    *openapi_types.UUID `json:"serviceId,omitempty"`

	// ServiceName Snapshotted at reservation time, like every field below it. A price
	// change or a rename must never rewrite what somebody already booked.
	ServiceName string        `json:"serviceName"`
	StartsAt    time.Time     `json:"startsAt"`
	Status      BookingStatus `json:"status"`
	UpdatedAt   *time.Time    `json:"updatedAt,omitempty"`
}

// BookingCancelledBy defines model for Booking.CancelledBy.
type BookingCancelledBy string

// BookingMode `instant` skips `pending` and confirms at creation; `request` waits for
// the provider to approve.
type BookingMode string

// BookingStatus defines model for BookingStatus.
type BookingStatus string

// BusinessHours defines model for BusinessHours.
type BusinessHours struct {
	// ClosesAt A wall-clock time in the provider's timezone.
	//
	// Example: 09:30
	ClosesAt TimeOfDay          `json:"closesAt"`
	Id       openapi_types.UUID `json:"id"`

	// OpensAt A wall-clock time in the provider's timezone.
	//
	// Example: 09:30
	OpensAt    TimeOfDay          `json:"opensAt"`
	ProviderId openapi_types.UUID `json:"providerId"`

	// ResourceId Null is the provider-wide default.
	ResourceId *openapi_types.UUID `json:"resourceId,omitempty"`

	// Weekday 0 = Sunday.
	Weekday int `json:"weekday"`
}

// Category defines model for Category.
type Category struct {
	CreatedAt *time.Time          `json:"createdAt,omitempty"`
	Icon      *string             `json:"icon,omitempty"`
	Id        openapi_types.UUID  `json:"id"`
	IsActive  bool                `json:"isActive"`
	Name      string              `json:"name"`
	ParentId  *openapi_types.UUID `json:"parentId,omitempty"`
	Slug      string              `json:"slug"`
	SortOrder *int                `json:"sortOrder,omitempty"`
	UpdatedAt *time.Time          `json:"updatedAt,omitempty"`
}

// CreateAttributeRequest defines model for CreateAttributeRequest.
type CreateAttributeRequest struct {
	// AppliesTo What the field describes. `service` fields are set by the provider on a
	// service; `booking` fields are asked of the customer at reservation time.
	AppliesTo  AttributeScope    `json:"appliesTo"`
	DataType   AttributeDataType `json:"dataType"`
	Filterable *bool             `json:"filterable,omitempty"`
	Key        string            `json:"key"`
	Label      string            `json:"label"`

	// Options Required and non-empty for `enum` and `multi_enum`.
	Options   *[]string `json:"options,omitempty"`
	Required  *bool     `json:"required,omitempty"`
	SortOrder *int      `json:"sortOrder,omitempty"`
}

// CreateBookingRequest Carries no price, duration or end time. The server derives all three
// from the catalog, so a client cannot assert its own totals.
type CreateBookingRequest struct {
	// Attributes Validated against the category's `booking` definitions.
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Note       *string                 `json:"note,omitempty"`

	// OptionIds Chosen add-ons. Required groups must be satisfied.
	OptionIds *[]openapi_types.UUID `json:"optionIds,omitempty"`
	ServiceId openapi_types.UUID    `json:"serviceId"`

	// StartsAt Must be one of the starts availability offered.
	StartsAt time.Time `json:"startsAt"`
}

// CreateBusinessHoursRequest defines model for CreateBusinessHoursRequest.
type CreateBusinessHoursRequest struct {
	// ClosesAt A wall-clock time in the provider's timezone.
	//
	// Example: 09:30
	ClosesAt TimeOfDay `json:"closesAt"`

	// OpensAt A wall-clock time in the provider's timezone.
	//
	// Example: 09:30
	OpensAt    TimeOfDay           `json:"opensAt"`
	ResourceId *openapi_types.UUID `json:"resourceId,omitempty"`
	Weekday    int                 `json:"weekday"`
}

// CreateOptionGroupRequest defines model for CreateOptionGroupRequest.
type CreateOptionGroupRequest struct {
	IsRequired    *bool                                 `json:"isRequired,omitempty"`
	MaxSelect     *int                                  `json:"maxSelect,omitempty"`
	MinSelect     *int                                  `json:"minSelect,omitempty"`
	Name          string                                `json:"name"`
	SelectionType CreateOptionGroupRequestSelectionType `json:"selectionType"`
	SortOrder     *int                                  `json:"sortOrder,omitempty"`
}

// CreateOptionGroupRequestSelectionType defines model for CreateOptionGroupRequest.SelectionType.
type CreateOptionGroupRequestSelectionType string

// CreateOptionRequest defines model for CreateOptionRequest.
type CreateOptionRequest struct {
	DurationDeltaMinutes *int   `json:"durationDeltaMinutes,omitempty"`
	IsActive             *bool  `json:"isActive,omitempty"`
	Name                 string `json:"name"`
	PriceDeltaCents      *int   `json:"priceDeltaCents,omitempty"`
	SortOrder            *int   `json:"sortOrder,omitempty"`
}

// CreateProviderRequest defines model for CreateProviderRequest.
type CreateProviderRequest struct {
	Address *string `json:"address,omitempty"`

	// BookingMode `instant` skips `pending` and confirms at creation; `request` waits for
	// the provider to approve.
	BookingMode    *BookingMode          `json:"bookingMode,omitempty"`
	CategoryIds    *[]openapi_types.UUID `json:"categoryIds,omitempty"`
	City           *string               `json:"city,omitempty"`
	Description    *string               `json:"description,omitempty"`
	Email          *openapi_types.Email  `json:"email,omitempty"`
	LicenseNumber  *string               `json:"licenseNumber,omitempty"`
	Location       *Location             `json:"location,omitempty"`
	MinLeadMinutes *int                  `json:"minLeadMinutes,omitempty"`
	Name           string                `json:"name"`
	Phone          *string               `json:"phone,omitempty"`

	// Slug Derived from the name if omitted.
	Slug     *string `json:"slug,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
}

// CreateResourceRequest defines model for CreateResourceRequest.
type CreateResourceRequest struct {
	IsActive   *bool                 `json:"isActive,omitempty"`
	Name       string                `json:"name"`
	ServiceIds *[]openapi_types.UUID `json:"serviceIds,omitempty"`
	UserId     *openapi_types.UUID   `json:"userId,omitempty"`
}

// CreateScheduleExceptionRequest defines model for CreateScheduleExceptionRequest.
type CreateScheduleExceptionRequest struct {
	// ClosesAt Required when `isClosed` is false, forbidden otherwise.
	ClosesAt *TimeOfDay         `json:"closesAt,omitempty"`
	Date     openapi_types.Date `json:"date"`
	IsClosed *bool              `json:"isClosed,omitempty"`

	// OpensAt Required when `isClosed` is false, forbidden otherwise.
	OpensAt    *TimeOfDay          `json:"opensAt,omitempty"`
	Reason     *string             `json:"reason,omitempty"`
	ResourceId *openapi_types.UUID `json:"resourceId,omitempty"`
}

// CreateServiceRequest defines model for CreateServiceRequest.
type CreateServiceRequest struct {
	Attributes      *map[string]interface{} `json:"attributes,omitempty"`
	BufferMinutes   *int                    `json:"bufferMinutes,omitempty"`
	CategoryId      openapi_types.UUID      `json:"categoryId"`
	Currency        *string                 `json:"currency,omitempty"`
	Description     *string                 `json:"description,omitempty"`
	DurationMinutes int                     `json:"durationMinutes"`
	IsActive        *bool                   `json:"isActive,omitempty"`
	Name            string                  `json:"name"`
	PriceCents      int                     `json:"priceCents"`
}

// Error defines model for Error.
type Error struct {
	// Code Stable machine-readable code. Clients switch on this, so it is part
	// of the contract and additive-only.
	//
	//
	// Example: SLOT_TAKEN
	Code ErrorCode `json:"code"`

	// Details Per-field problems, keyed by attribute. Present on validation
	// failures only; a client that reads just `message` and `code` is
	// unaffected by it.
	Details *map[string]string `json:"details,omitempty"`

	// Message Human-readable and safe to show a user.
	//
	// Example: That slot was just taken
	Message string `json:"message"`
}

// ErrorCode Stable machine-readable code. Clients switch on this, so it is part
// of the contract and additive-only.
//
// Example: SLOT_TAKEN
type ErrorCode string

// Invitation defines model for Invitation.
type Invitation struct {
	AcceptedAt *time.Time           `json:"acceptedAt,omitempty"`
	CreatedAt  *time.Time           `json:"createdAt,omitempty"`
	Email      *openapi_types.Email `json:"email,omitempty"`
	ExpiresAt  *time.Time           `json:"expiresAt,omitempty"`
	Id         *openapi_types.UUID  `json:"id,omitempty"`
	ProviderId *openapi_types.UUID  `json:"providerId,omitempty"`
	Role       *MemberRole          `json:"role,omitempty"`

	// Token Returned only in the response to creating the invitation. Only its
	// hash is stored, so it is never readable again.
	Token *string `json:"token,omitempty"`
}

// Location defines model for Location.
type Location struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

// Member defines model for Member.
type Member struct {
	CreatedAt  *time.Time           `json:"createdAt,omitempty"`
	Email      *openapi_types.Email `json:"email,omitempty"`
	Name       *string              `json:"name,omitempty"`
	Phone      *string              `json:"phone,omitempty"`
	ProviderId *openapi_types.UUID  `json:"providerId,omitempty"`
	Role       *MemberRole          `json:"role,omitempty"`
	UserId     *openapi_types.UUID  `json:"userId,omitempty"`
}

// MemberRole defines model for MemberRole.
type MemberRole string

// Membership One organization the caller belongs to. `name`, `slug` and `status`
// are carried here so a client can name the organizations someone owns
// without a request per membership; the JWT claim keeps the smaller
// `providerId` + `role` pair.
type Membership struct {
	Name       string             `json:"name"`
	ProviderId openapi_types.UUID `json:"providerId"`
	Role       MemberRole         `json:"role"`
	Slug       string             `json:"slug"`
	Status     ProviderStatus     `json:"status"`
}

// Option defines model for Option.
type Option struct {
	// DurationDeltaMinutes Added to the service's duration when chosen.
	DurationDeltaMinutes int                `json:"durationDeltaMinutes"`
	GroupId              openapi_types.UUID `json:"groupId"`
	Id                   openapi_types.UUID `json:"id"`
	IsActive             bool               `json:"isActive"`

	// Name Example: SUV
	Name string `json:"name"`

	// PriceDeltaCents Added to the service's price when chosen.
	PriceDeltaCents int  `json:"priceDeltaCents"`
	SortOrder       *int `json:"sortOrder,omitempty"`
}

// OptionGroup defines model for OptionGroup.
type OptionGroup struct {
	Id         openapi_types.UUID `json:"id"`
	IsRequired bool               `json:"isRequired"`
	MaxSelect  *int               `json:"maxSelect,omitempty"`
	MinSelect  *int               `json:"minSelect,omitempty"`

	// Name Example: Vehicle size
	Name    string    `json:"name"`
	Options *[]Option `json:"options,omitempty"`

	// SelectionType Radio versus checkbox, with one mechanism.
	SelectionType OptionGroupSelectionType `json:"selectionType"`
	ServiceId     openapi_types.UUID       `json:"serviceId"`
	SortOrder     *int                     `json:"sortOrder,omitempty"`
}

// OptionGroupSelectionType Radio versus checkbox, with one mechanism.
type OptionGroupSelectionType string

// Page defines model for Page.
type Page struct {
	Limit  *int   `json:"limit,omitempty"`
	Offset *int   `json:"offset,omitempty"`
	Total  *int64 `json:"total,omitempty"`
}

// Provider defines model for Provider.
type Provider struct {
	Address *string `json:"address,omitempty"`

	// BookingMode `instant` skips `pending` and confirms at creation; `request` waits for
	// the provider to approve.
	BookingMode BookingMode `json:"bookingMode"`
	City        *string     `json:"city,omitempty"`

	// CoverUrl The wide banner behind the provider's header.
	CoverUrl      *string            `json:"coverUrl,omitempty"`
	CreatedAt     *time.Time         `json:"createdAt,omitempty"`
	Description   *string            `json:"description,omitempty"`
	Email         *string            `json:"email,omitempty"`
	Id            openapi_types.UUID `json:"id"`
	LicenseNumber *string            `json:"licenseNumber,omitempty"`
	Location      *Location          `json:"location,omitempty"`

	// LogoUrl The square mark. Opaque — relative while uploads are stored
	// locally, absolute once a hosted provider serves them.
	LogoUrl *string `json:"logoUrl,omitempty"`

	// MinLeadMinutes Slots sooner than this from now are not offered.
	MinLeadMinutes *int           `json:"minLeadMinutes,omitempty"`
	Name           string         `json:"name"`
	Phone          *string        `json:"phone,omitempty"`
	RatingAvg      *float64       `json:"ratingAvg,omitempty"`
	RatingCount    *int           `json:"ratingCount,omitempty"`
	Slug           string         `json:"slug"`
	Status         ProviderStatus `json:"status"`

	// Timezone IANA zone; all slot maths happens here.
	//
	// Example: Africa/Addis_Ababa
	Timezone  string     `json:"timezone"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// ProviderStatus defines model for ProviderStatus.
type ProviderStatus string

// ProviderSummary defines model for ProviderSummary.
type ProviderSummary struct {
	City     *string             `json:"city,omitempty"`
	Id       *openapi_types.UUID `json:"id,omitempty"`
	LogoUrl  *string             `json:"logoUrl,omitempty"`
	Name     *string             `json:"name,omitempty"`
	Slug     *string             `json:"slug,omitempty"`
	Timezone *string             `json:"timezone,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// ReplaceBusinessHoursRequest defines model for ReplaceBusinessHoursRequest.
type ReplaceBusinessHoursRequest struct {
	// Hours Every opening span for the scope. A weekday with no span here is
	// closed; an empty array closes the scope entirely. More than one span
	// on a day is a split shift — a lunch break, say — as long as they do
	// not overlap.
	Hours []struct {
		// ClosesAt A wall-clock time in the provider's timezone.
		//
		// Example: 09:30
		ClosesAt TimeOfDay `json:"closesAt"`

		// OpensAt A wall-clock time in the provider's timezone.
		//
		// Example: 09:30
		OpensAt TimeOfDay `json:"opensAt"`
		Weekday int       `json:"weekday"`
	} `json:"hours"`

	// ResourceId The scope being rewritten. Null is the provider-wide default.
	ResourceId *openapi_types.UUID `json:"resourceId,omitempty"`
}

// Resource defines model for Resource.
type Resource struct {
	CreatedAt *time.Time         `json:"createdAt,omitempty"`
	Id        openapi_types.UUID `json:"id"`
	IsActive  bool               `json:"isActive"`

	// Name Example: Bay 1
	Name       string                `json:"name"`
	ProviderId openapi_types.UUID    `json:"providerId"`
	ServiceIds *[]openapi_types.UUID `json:"serviceIds,omitempty"`
	UpdatedAt  *time.Time            `json:"updatedAt,omitempty"`

	// UserId The staff account this resource belongs to, if any.
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// ScheduleException defines model for ScheduleException.
type ScheduleException struct {
	// ClosesAt A wall-clock time in the provider's timezone.
	//
	// Example: 09:30
	ClosesAt *TimeOfDay         `json:"closesAt,omitempty"`
	Date     openapi_types.Date `json:"date"`
	Id       openapi_types.UUID `json:"id"`
	IsClosed bool               `json:"isClosed"`

	// OpensAt A wall-clock time in the provider's timezone.
	//
	// Example: 09:30
	OpensAt    *TimeOfDay         `json:"opensAt,omitempty"`
	ProviderId openapi_types.UUID `json:"providerId"`
	Reason     *string            `json:"reason,omitempty"`

	// ResourceId Null applies to the whole provider.
	ResourceId *openapi_types.UUID `json:"resourceId,omitempty"`
}

// Service defines model for Service.
type Service struct {
	// Attributes Validated against the category's `service` definitions.
	Attributes *map[string]interface{} `json:"attributes,omitempty"`

	// BufferMinutes Added after the service; occupies the resource but is not priced.
	BufferMinutes *int               `json:"bufferMinutes,omitempty"`
	CategoryId    openapi_types.UUID `json:"categoryId"`

	// CategoryName Populated by the list endpoints, which join it anyway in order to
	// sort by it. Absent elsewhere.
	CategoryName *string    `json:"categoryName,omitempty"`
	CreatedAt    *time.Time `json:"createdAt,omitempty"`
	Currency     string     `json:"currency"`
	Description  *string    `json:"description,omitempty"`

	// DurationMinutes The scheduling engine's only real input.
	DurationMinutes int                `json:"durationMinutes"`
	Id              openapi_types.UUID `json:"id"`
	ImageUrl        *string            `json:"imageUrl,omitempty"`
	IsActive        bool               `json:"isActive"`
	Name            string             `json:"name"`

	// OptionGroups Present on the detail endpoints only.
	OptionGroups *[]OptionGroup `json:"optionGroups,omitempty"`

	// PriceCents Minor units. 24500 = 245.00 ETB.
	PriceCents int                `json:"priceCents"`
	ProviderId openapi_types.UUID `json:"providerId"`
	UpdatedAt  *time.Time         `json:"updatedAt,omitempty"`
}

// ServiceImage defines model for ServiceImage.
type ServiceImage struct {
	Caption   *string            `json:"caption,omitempty"`
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`

	// ImageUrl Opaque. Relative when uploads are stored locally, absolute when a
	// hosted provider serves them. Never build one client-side.
	ImageUrl  string             `json:"imageUrl"`
	ServiceId openapi_types.UUID `json:"serviceId"`
	SortOrder int                `json:"sortOrder"`
}

// Session defines model for Session.
type Session struct {
	// Memberships Empty for a customer. That is the whole difference.
	Memberships []Membership `json:"memberships"`
	Tokens      Tokens       `json:"tokens"`
	User        User         `json:"user"`
}

// SignInRequest defines model for SignInRequest.
type SignInRequest struct {
	ClientType *SignInRequestClientType `json:"clientType,omitempty"`
	Email      openapi_types.Email      `json:"email"`
	Password   string                   `json:"password"`
}

// SignInRequestClientType defines model for SignInRequest.ClientType.
type SignInRequestClientType string

// SignUpRequest defines model for SignUpRequest.
type SignUpRequest struct {
	// ClientType Decides the refresh-token lifetime.
	ClientType *SignUpRequestClientType `json:"clientType,omitempty"`
	Email      openapi_types.Email      `json:"email"`
	Name       string                   `json:"name"`
	Password   string                   `json:"password"`
	Phone      *string                  `json:"phone,omitempty"`
}

// SignUpRequestClientType Decides the refresh-token lifetime.
type SignUpRequestClientType string

// Slot defines model for Slot.
type Slot struct {
	// ResourceIds The resources that could take this start.
	ResourceIds []openapi_types.UUID `json:"resourceIds"`
	StartsAt    time.Time            `json:"startsAt"`
}

// Stats defines model for Stats.
type Stats struct {
	Cancelled             *int64 `json:"cancelled,omitempty"`
	Completed             *int64 `json:"completed,omitempty"`
	CompletedRevenueCents *int64 `json:"completedRevenueCents,omitempty"`
	Confirmed             *int64 `json:"confirmed,omitempty"`
	InProgress            *int64 `json:"inProgress,omitempty"`
	NoShow                *int64 `json:"noShow,omitempty"`
	Pending               *int64 `json:"pending,omitempty"`
}

// TimeOfDay A wall-clock time in the provider's timezone.
//
// Example: 09:30
type TimeOfDay = string

// Tokens defines model for Tokens.
type Tokens struct {
	// AccessToken A 15-minute JWT.
	AccessToken string    `json:"accessToken"`
	ExpiresAt   time.Time `json:"expiresAt"`

	// RefreshToken Opaque and single-use. 30 days for `web`, 90 for `mobile`. Store it
	// in `expo-secure-store` on mobile, never `AsyncStorage`.
	RefreshToken string          `json:"refreshToken"`
	TokenType    TokensTokenType `json:"tokenType"`
}

// TokensTokenType defines model for Tokens.TokenType.
type TokensTokenType string

// UpdateProviderRequest Omitted fields are left unchanged.
type UpdateProviderRequest struct {
	Address *string `json:"address,omitempty"`

	// BookingMode `instant` skips `pending` and confirms at creation; `request` waits for
	// the provider to approve.
	BookingMode    *BookingMode         `json:"bookingMode,omitempty"`
	City           *string              `json:"city,omitempty"`
	Description    *string              `json:"description,omitempty"`
	Email          *openapi_types.Email `json:"email,omitempty"`
	LicenseNumber  *string              `json:"licenseNumber,omitempty"`
	Location       *Location            `json:"location,omitempty"`
	MinLeadMinutes *int                 `json:"minLeadMinutes,omitempty"`
	Name           *string              `json:"name,omitempty"`
	Phone          *string              `json:"phone,omitempty"`
	Timezone       *string              `json:"timezone,omitempty"`
}

// UpdateServiceRequest Omitted fields are left unchanged.
type UpdateServiceRequest struct {
	Attributes      *map[string]interface{} `json:"attributes,omitempty"`
	BufferMinutes   *int                    `json:"bufferMinutes,omitempty"`
	CategoryId      *openapi_types.UUID     `json:"categoryId,omitempty"`
	Currency        *string                 `json:"currency,omitempty"`
	Description     *string                 `json:"description,omitempty"`
	DurationMinutes *int                    `json:"durationMinutes,omitempty"`
	IsActive        *bool                   `json:"isActive,omitempty"`
	Name            *string                 `json:"name,omitempty"`
	PriceCents      *int                    `json:"priceCents,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt     time.Time           `json:"createdAt"`
	Email         openapi_types.Email `json:"email"`
	EmailVerified bool                `json:"emailVerified"`
	Id            openapi_types.UUID  `json:"id"`
	Name          string              `json:"name"`
	Phone         *string             `json:"phone,omitempty"`
	PlatformRole  UserPlatformRole    `json:"platformRole"`
	UpdatedAt     *time.Time          `json:"updatedAt,omitempty"`
}

// UserPlatformRole defines model for User.PlatformRole.
type UserPlatformRole string

// BookingId defines model for BookingId.
type BookingId = openapi_types.UUID

// CategoryId defines model for CategoryId.
type CategoryId = openapi_types.UUID

// GroupId defines model for GroupId.
type GroupId = openapi_types.UUID

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// OrganizationId defines model for OrganizationId.
type OrganizationId = openapi_types.UUID

// ProviderId defines model for ProviderId.
type ProviderId = openapi_types.UUID

// ResourceId defines model for ResourceId.
type ResourceId = openapi_types.UUID

// ServiceId defines model for ServiceId.
type ServiceId = openapi_types.UUID

// BookingTransitioned defines model for BookingTransitioned.
type BookingTransitioned = Booking

// Forbidden defines model for Forbidden.
type Forbidden = Error

// InvalidTransition defines model for InvalidTransition.
type InvalidTransition = Error

// NotAMember defines model for NotAMember.
type NotAMember = Error

// NotFound defines model for NotFound.
type NotFound = Error

// OrgRequired defines model for OrgRequired.
type OrgRequired = Error

// Unauthenticated defines model for Unauthenticated.
type Unauthenticated = Error

// ValidationError defines model for ValidationError.
type ValidationError = Error

// GetApiV1AdminBookingsParams defines parameters for GetApiV1AdminBookings.
type GetApiV1AdminBookingsParams struct {
	Status     *BookingStatus      `form:"status,omitempty" json:"status,omitempty"`
	ProviderId *openapi_types.UUID `form:"providerId,omitempty" json:"providerId,omitempty"`
	Limit      *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset             `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostApiV1AdminCategoriesJSONBody defines parameters for PostApiV1AdminCategories.
type PostApiV1AdminCategoriesJSONBody struct {
	Icon     *string             `json:"icon,omitempty"`
	IsActive *bool               `json:"isActive,omitempty"`
	Name     string              `json:"name"`
	ParentId *openapi_types.UUID `json:"parentId,omitempty"`

	// Slug Derived from the name if omitted.
	Slug      *string `json:"slug,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

// PatchApiV1AdminCategoriesCategoryIdJSONBody defines parameters for PatchApiV1AdminCategoriesCategoryId.
type PatchApiV1AdminCategoriesCategoryIdJSONBody struct {
	Icon      *string `json:"icon,omitempty"`
	IsActive  *bool   `json:"isActive,omitempty"`
	Name      *string `json:"name,omitempty"`
	Slug      *string `json:"slug,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

// PatchApiV1AdminCategoriesCategoryIdAttributesAttributeIdJSONBody defines parameters for PatchApiV1AdminCategoriesCategoryIdAttributesAttributeId.
type PatchApiV1AdminCategoriesCategoryIdAttributesAttributeIdJSONBody struct {
	DataType   *AttributeDataType `json:"dataType,omitempty"`
	Filterable *bool              `json:"filterable,omitempty"`
	Label      *string            `json:"label,omitempty"`
	Options    *[]string          `json:"options,omitempty"`
	Required   *bool              `json:"required,omitempty"`
	SortOrder  *int               `json:"sortOrder,omitempty"`
}

// GetApiV1AdminProvidersParams defines parameters for GetApiV1AdminProviders.
type GetApiV1AdminProvidersParams struct {
	Status *ProviderStatus `form:"status,omitempty" json:"status,omitempty"`
	Search *string         `form:"search,omitempty" json:"search,omitempty"`
	Limit  *Limit          `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset         `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetApiV1AdminUsersParams defines parameters for GetApiV1AdminUsers.
type GetApiV1AdminUsersParams struct {
	// Search Matches name or email.
	Search *string `form:"search,omitempty" json:"search,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostApiV1AuthResendVerificationJSONBody defines parameters for PostApiV1AuthResendVerification.
type PostApiV1AuthResendVerificationJSONBody struct {
	Email openapi_types.Email `json:"email"`
}

// PostApiV1AuthVerifyEmailJSONBody defines parameters for PostApiV1AuthVerifyEmail.
type PostApiV1AuthVerifyEmailJSONBody struct {
	// Code Example: 418205
	Code  string              `json:"code"`
	Email openapi_types.Email `json:"email"`
}

// GetApiV1MeBookingsParams defines parameters for GetApiV1MeBookings.
type GetApiV1MeBookingsParams struct {
	Status *BookingStatus `form:"status,omitempty" json:"status,omitempty"`
	Limit  *Limit         `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *Offset        `form:"offset,omitempty" json:"offset,omitempty"`
}

// PostApiV1MeBookingsBookingIdCancelJSONBody defines parameters for PostApiV1MeBookingsBookingIdCancel.
type PostApiV1MeBookingsBookingIdCancelJSONBody struct {
	Reason *string `json:"reason,omitempty"`
}

// PostApiV1MeDevicesJSONBody defines parameters for PostApiV1MeDevices.
type PostApiV1MeDevicesJSONBody struct {
	FcmToken string `json:"fcmToken"`
}

// PostApiV1MeInvitationsAcceptJSONBody defines parameters for PostApiV1MeInvitationsAccept.
type PostApiV1MeInvitationsAcceptJSONBody struct {
	Token string `json:"token"`
}

// PatchApiV1MeProfileJSONBody defines parameters for PatchApiV1MeProfile.
type PatchApiV1MeProfileJSONBody struct {
	Name  *string `json:"name,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

// GetApiV1OrgBookingsParams defines parameters for GetApiV1OrgBookings.
type GetApiV1OrgBookingsParams struct {
	// Date One local day in the provider's timezone.
	Date       *openapi_types.Date `form:"date,omitempty" json:"date,omitempty"`
	Status     *BookingStatus      `form:"status,omitempty" json:"status,omitempty"`
	ResourceId *openapi_types.UUID `form:"resourceId,omitempty" json:"resourceId,omitempty"`
	Limit      *Limit              `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *Offset             `form:"offset,omitempty" json:"offset,omitempty"`

	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgBookingsJSONBody defines parameters for PostApiV1OrgBookings.
type PostApiV1OrgBookingsJSONBody struct {
	// Attributes Validated against the category's `booking` definitions.
	Attributes    *map[string]interface{} `json:"attributes,omitempty"`
	CustomerName  *string                 `json:"customerName,omitempty"`
	CustomerPhone *string                 `json:"customerPhone,omitempty"`
	Note          *string                 `json:"note,omitempty"`

	// OptionIds Chosen add-ons. Required groups must be satisfied.
	OptionIds *[]openapi_types.UUID `json:"optionIds,omitempty"`

	// ResourceId Pin the booking to one resource.
	ResourceId *openapi_types.UUID `json:"resourceId,omitempty"`
	ServiceId  openapi_types.UUID  `json:"serviceId"`

	// StartsAt Must be one of the starts availability offered.
	StartsAt time.Time `json:"startsAt"`
}

// PostApiV1OrgBookingsParams defines parameters for PostApiV1OrgBookings.
type PostApiV1OrgBookingsParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgBookingsBookingIdParams defines parameters for GetApiV1OrgBookingsBookingId.
type GetApiV1OrgBookingsBookingIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgBookingsBookingIdCancelJSONBody defines parameters for PostApiV1OrgBookingsBookingIdCancel.
type PostApiV1OrgBookingsBookingIdCancelJSONBody struct {
	Reason *string `json:"reason,omitempty"`
}

// PostApiV1OrgBookingsBookingIdCancelParams defines parameters for PostApiV1OrgBookingsBookingIdCancel.
type PostApiV1OrgBookingsBookingIdCancelParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgBookingsBookingIdCompleteParams defines parameters for PostApiV1OrgBookingsBookingIdComplete.
type PostApiV1OrgBookingsBookingIdCompleteParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgBookingsBookingIdConfirmParams defines parameters for PostApiV1OrgBookingsBookingIdConfirm.
type PostApiV1OrgBookingsBookingIdConfirmParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgBookingsBookingIdNoShowParams defines parameters for PostApiV1OrgBookingsBookingIdNoShow.
type PostApiV1OrgBookingsBookingIdNoShowParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgBookingsBookingIdStartParams defines parameters for PostApiV1OrgBookingsBookingIdStart.
type PostApiV1OrgBookingsBookingIdStartParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgBusinessHoursParams defines parameters for GetApiV1OrgBusinessHours.
type GetApiV1OrgBusinessHoursParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgBusinessHoursParams defines parameters for PostApiV1OrgBusinessHours.
type PostApiV1OrgBusinessHoursParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PutApiV1OrgBusinessHoursParams defines parameters for PutApiV1OrgBusinessHours.
type PutApiV1OrgBusinessHoursParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgBusinessHoursHoursIdParams defines parameters for DeleteApiV1OrgBusinessHoursHoursId.
type DeleteApiV1OrgBusinessHoursHoursIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PatchApiV1OrgBusinessHoursHoursIdJSONBody defines parameters for PatchApiV1OrgBusinessHoursHoursId.
type PatchApiV1OrgBusinessHoursHoursIdJSONBody struct {
	// ClosesAt A wall-clock time in the provider's timezone.
	//
	// Example: 09:30
	ClosesAt *TimeOfDay `json:"closesAt,omitempty"`

	// OpensAt A wall-clock time in the provider's timezone.
	//
	// Example: 09:30
	OpensAt *TimeOfDay `json:"opensAt,omitempty"`
	Weekday *int       `json:"weekday,omitempty"`
}

// PatchApiV1OrgBusinessHoursHoursIdParams defines parameters for PatchApiV1OrgBusinessHoursHoursId.
type PatchApiV1OrgBusinessHoursHoursIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgInvitationsParams defines parameters for GetApiV1OrgInvitations.
type GetApiV1OrgInvitationsParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgInvitationsJSONBody defines parameters for PostApiV1OrgInvitations.
type PostApiV1OrgInvitationsJSONBody struct {
	Email openapi_types.Email `json:"email"`
	Role  MemberRole          `json:"role"`
}

// PostApiV1OrgInvitationsParams defines parameters for PostApiV1OrgInvitations.
type PostApiV1OrgInvitationsParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgInvitationsInvitationIdParams defines parameters for DeleteApiV1OrgInvitationsInvitationId.
type DeleteApiV1OrgInvitationsInvitationIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgMembersParams defines parameters for GetApiV1OrgMembers.
type GetApiV1OrgMembersParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgMembersJSONBody defines parameters for PostApiV1OrgMembers.
type PostApiV1OrgMembersJSONBody struct {
	Email openapi_types.Email `json:"email"`
	Name  string              `json:"name"`

	// Password Omit to have one generated.
	Password *string                         `json:"password,omitempty"`
	Phone    *string                         `json:"phone,omitempty"`
	Role     PostApiV1OrgMembersJSONBodyRole `json:"role"`
}

// PostApiV1OrgMembersParams defines parameters for PostApiV1OrgMembers.
type PostApiV1OrgMembersParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgMembersJSONBodyRole defines parameters for PostApiV1OrgMembers.
type PostApiV1OrgMembersJSONBodyRole string

// DeleteApiV1OrgMembersUserIdParams defines parameters for DeleteApiV1OrgMembersUserId.
type DeleteApiV1OrgMembersUserIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PatchApiV1OrgMembersUserIdJSONBody defines parameters for PatchApiV1OrgMembersUserId.
type PatchApiV1OrgMembersUserIdJSONBody struct {
	Role MemberRole `json:"role"`
}

// PatchApiV1OrgMembersUserIdParams defines parameters for PatchApiV1OrgMembersUserId.
type PatchApiV1OrgMembersUserIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgProfileParams defines parameters for GetApiV1OrgProfile.
type GetApiV1OrgProfileParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PatchApiV1OrgProfileParams defines parameters for PatchApiV1OrgProfile.
type PatchApiV1OrgProfileParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgProfileImagesKindParams defines parameters for DeleteApiV1OrgProfileImagesKind.
type DeleteApiV1OrgProfileImagesKindParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PutApiV1OrgProfileImagesKindMultipartBody defines parameters for PutApiV1OrgProfileImagesKind.
type PutApiV1OrgProfileImagesKindMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// PutApiV1OrgProfileImagesKindParams defines parameters for PutApiV1OrgProfileImagesKind.
type PutApiV1OrgProfileImagesKindParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgResourcesParams defines parameters for GetApiV1OrgResources.
type GetApiV1OrgResourcesParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgResourcesParams defines parameters for PostApiV1OrgResources.
type PostApiV1OrgResourcesParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgResourcesResourceIdParams defines parameters for DeleteApiV1OrgResourcesResourceId.
type DeleteApiV1OrgResourcesResourceIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PatchApiV1OrgResourcesResourceIdJSONBody defines parameters for PatchApiV1OrgResourcesResourceId.
type PatchApiV1OrgResourcesResourceIdJSONBody struct {
	IsActive *bool   `json:"isActive,omitempty"`
	Name     *string `json:"name,omitempty"`

	// UnassignUser Detaches the staff login, leaving the resource nobody's in
	// particular. Every other field here means "leave it alone"
	// when omitted, so without this there is no way to say it;
	// set, it overrides `userId`.
	UnassignUser *bool `json:"unassignUser,omitempty"`

	// UserId Attaches the resource to a team member's login.
	UserId *openapi_types.UUID `json:"userId,omitempty"`
}

// PatchApiV1OrgResourcesResourceIdParams defines parameters for PatchApiV1OrgResourcesResourceId.
type PatchApiV1OrgResourcesResourceIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgResourcesResourceIdServicesServiceIdParams defines parameters for DeleteApiV1OrgResourcesResourceIdServicesServiceId.
type DeleteApiV1OrgResourcesResourceIdServicesServiceIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PutApiV1OrgResourcesResourceIdServicesServiceIdParams defines parameters for PutApiV1OrgResourcesResourceIdServicesServiceId.
type PutApiV1OrgResourcesResourceIdServicesServiceIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgScheduleExceptionsParams defines parameters for GetApiV1OrgScheduleExceptions.
type GetApiV1OrgScheduleExceptionsParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`
	To   *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgScheduleExceptionsParams defines parameters for PostApiV1OrgScheduleExceptions.
type PostApiV1OrgScheduleExceptionsParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgScheduleExceptionsExceptionIdParams defines parameters for DeleteApiV1OrgScheduleExceptionsExceptionId.
type DeleteApiV1OrgScheduleExceptionsExceptionIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgServicesParams defines parameters for GetApiV1OrgServices.
type GetApiV1OrgServicesParams struct {
	// Search Matches name or description, case-insensitively.
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// IsActive Omit for either.
	IsActive   *GetApiV1OrgServicesParamsIsActive `form:"isActive,omitempty" json:"isActive,omitempty"`
	CategoryId *openapi_types.UUID                `form:"categoryId,omitempty" json:"categoryId,omitempty"`
	Sort       *GetApiV1OrgServicesParamsSort     `form:"sort,omitempty" json:"sort,omitempty"`
	Limit      *int                               `form:"limit,omitempty" json:"limit,omitempty"`
	Offset     *int                               `form:"offset,omitempty" json:"offset,omitempty"`

	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgServicesParamsIsActive defines parameters for GetApiV1OrgServices.
type GetApiV1OrgServicesParamsIsActive string

// GetApiV1OrgServicesParamsSort defines parameters for GetApiV1OrgServices.
type GetApiV1OrgServicesParamsSort string

// PostApiV1OrgServicesParams defines parameters for PostApiV1OrgServices.
type PostApiV1OrgServicesParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgServicesServiceIdParams defines parameters for DeleteApiV1OrgServicesServiceId.
type DeleteApiV1OrgServicesServiceIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgServicesServiceIdParams defines parameters for GetApiV1OrgServicesServiceId.
type GetApiV1OrgServicesServiceIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PatchApiV1OrgServicesServiceIdParams defines parameters for PatchApiV1OrgServicesServiceId.
type PatchApiV1OrgServicesServiceIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgServicesServiceIdMediaParams defines parameters for GetApiV1OrgServicesServiceIdMedia.
type GetApiV1OrgServicesServiceIdMediaParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgServicesServiceIdMediaMultipartBody defines parameters for PostApiV1OrgServicesServiceIdMedia.
type PostApiV1OrgServicesServiceIdMediaMultipartBody struct {
	Caption *string            `json:"caption,omitempty"`
	File    openapi_types.File `json:"file"`
}

// PostApiV1OrgServicesServiceIdMediaParams defines parameters for PostApiV1OrgServicesServiceIdMedia.
type PostApiV1OrgServicesServiceIdMediaParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgServicesServiceIdMediaMediaIdParams defines parameters for DeleteApiV1OrgServicesServiceIdMediaMediaId.
type DeleteApiV1OrgServicesServiceIdMediaMediaIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PatchApiV1OrgServicesServiceIdMediaMediaIdJSONBody defines parameters for PatchApiV1OrgServicesServiceIdMediaMediaId.
type PatchApiV1OrgServicesServiceIdMediaMediaIdJSONBody struct {
	Caption   *string `json:"caption,omitempty"`
	SortOrder *int    `json:"sortOrder,omitempty"`
}

// PatchApiV1OrgServicesServiceIdMediaMediaIdParams defines parameters for PatchApiV1OrgServicesServiceIdMediaMediaId.
type PatchApiV1OrgServicesServiceIdMediaMediaIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgServicesServiceIdOptionGroupsParams defines parameters for GetApiV1OrgServicesServiceIdOptionGroups.
type GetApiV1OrgServicesServiceIdOptionGroupsParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgServicesServiceIdOptionGroupsParams defines parameters for PostApiV1OrgServicesServiceIdOptionGroups.
type PostApiV1OrgServicesServiceIdOptionGroupsParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgServicesServiceIdOptionGroupsGroupIdParams defines parameters for DeleteApiV1OrgServicesServiceIdOptionGroupsGroupId.
type DeleteApiV1OrgServicesServiceIdOptionGroupsGroupIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdParams defines parameters for PatchApiV1OrgServicesServiceIdOptionGroupsGroupId.
type PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PostApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsParams defines parameters for PostApiV1OrgServicesServiceIdOptionGroupsGroupIdOptions.
type PostApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// DeleteApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionIdParams defines parameters for DeleteApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionId.
type DeleteApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionIdParams defines parameters for PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionId.
type PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionIdParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgStatsCatalogParams defines parameters for GetApiV1OrgStatsCatalog.
type GetApiV1OrgStatsCatalogParams struct {
	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1OrgStatsSummaryParams defines parameters for GetApiV1OrgStatsSummary.
type GetApiV1OrgStatsSummaryParams struct {
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Inclusive.
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// XOrganizationId The organization to act within. Client-supplied and never trusted: every
	// `/org/*` request re-reads the caller's membership from the database
	// before any org-scoped data is touched.
	XOrganizationId OrganizationId `json:"x-organization-id"`
}

// GetApiV1PublicCategoriesCategoryIdAttributesParams defines parameters for GetApiV1PublicCategoriesCategoryIdAttributes.
type GetApiV1PublicCategoriesCategoryIdAttributesParams struct {
	// AppliesTo Narrow to one scope. Absent returns all three.
	AppliesTo *GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo `form:"appliesTo,omitempty" json:"appliesTo,omitempty"`
}

// GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo defines parameters for GetApiV1PublicCategoriesCategoryIdAttributes.
type GetApiV1PublicCategoriesCategoryIdAttributesParamsAppliesTo string

// GetApiV1PublicServicesServiceIdAvailabilityParams defines parameters for GetApiV1PublicServicesServiceIdAvailability.
type GetApiV1PublicServicesServiceIdAvailabilityParams struct {
	// Date Local calendar date in the provider's timezone.
	Date openapi_types.Date `form:"date" json:"date"`

	// OptionIds Comma-separated option ids. Required groups must be satisfied.
	OptionIds *string `form:"optionIds,omitempty" json:"optionIds,omitempty"`
}

// PostApiV1AdminCategoriesJSONRequestBody defines body for PostApiV1AdminCategories for application/json ContentType.
type PostApiV1AdminCategoriesJSONRequestBody PostApiV1AdminCategoriesJSONBody

// PatchApiV1AdminCategoriesCategoryIdJSONRequestBody defines body for PatchApiV1AdminCategoriesCategoryId for application/json ContentType.
type PatchApiV1AdminCategoriesCategoryIdJSONRequestBody PatchApiV1AdminCategoriesCategoryIdJSONBody

// PostApiV1AdminCategoriesCategoryIdAttributesJSONRequestBody defines body for PostApiV1AdminCategoriesCategoryIdAttributes for application/json ContentType.
type PostApiV1AdminCategoriesCategoryIdAttributesJSONRequestBody = CreateAttributeRequest

// PatchApiV1AdminCategoriesCategoryIdAttributesAttributeIdJSONRequestBody defines body for PatchApiV1AdminCategoriesCategoryIdAttributesAttributeId for application/json ContentType.
type PatchApiV1AdminCategoriesCategoryIdAttributesAttributeIdJSONRequestBody PatchApiV1AdminCategoriesCategoryIdAttributesAttributeIdJSONBody

// PostApiV1AdminProvidersJSONRequestBody defines body for PostApiV1AdminProviders for application/json ContentType.
type PostApiV1AdminProvidersJSONRequestBody = CreateProviderRequest

// PostApiV1AuthRefreshJSONRequestBody defines body for PostApiV1AuthRefresh for application/json ContentType.
type PostApiV1AuthRefreshJSONRequestBody = RefreshRequest

// PostApiV1AuthResendVerificationJSONRequestBody defines body for PostApiV1AuthResendVerification for application/json ContentType.
type PostApiV1AuthResendVerificationJSONRequestBody PostApiV1AuthResendVerificationJSONBody

// PostApiV1AuthSignInJSONRequestBody defines body for PostApiV1AuthSignIn for application/json ContentType.
type PostApiV1AuthSignInJSONRequestBody = SignInRequest

// PostApiV1AuthSignOutJSONRequestBody defines body for PostApiV1AuthSignOut for application/json ContentType.
type PostApiV1AuthSignOutJSONRequestBody = RefreshRequest

// PostApiV1AuthSignUpJSONRequestBody defines body for PostApiV1AuthSignUp for application/json ContentType.
type PostApiV1AuthSignUpJSONRequestBody = SignUpRequest

// PostApiV1AuthVerifyEmailJSONRequestBody defines body for PostApiV1AuthVerifyEmail for application/json ContentType.
type PostApiV1AuthVerifyEmailJSONRequestBody PostApiV1AuthVerifyEmailJSONBody

// PostApiV1MeBookingsJSONRequestBody defines body for PostApiV1MeBookings for application/json ContentType.
type PostApiV1MeBookingsJSONRequestBody = CreateBookingRequest

// PostApiV1MeBookingsBookingIdCancelJSONRequestBody defines body for PostApiV1MeBookingsBookingIdCancel for application/json ContentType.
type PostApiV1MeBookingsBookingIdCancelJSONRequestBody PostApiV1MeBookingsBookingIdCancelJSONBody

// PostApiV1MeDevicesJSONRequestBody defines body for PostApiV1MeDevices for application/json ContentType.
type PostApiV1MeDevicesJSONRequestBody PostApiV1MeDevicesJSONBody

// PostApiV1MeInvitationsAcceptJSONRequestBody defines body for PostApiV1MeInvitationsAccept for application/json ContentType.
type PostApiV1MeInvitationsAcceptJSONRequestBody PostApiV1MeInvitationsAcceptJSONBody

// PatchApiV1MeProfileJSONRequestBody defines body for PatchApiV1MeProfile for application/json ContentType.
type PatchApiV1MeProfileJSONRequestBody PatchApiV1MeProfileJSONBody

// PostApiV1MeProvidersJSONRequestBody defines body for PostApiV1MeProviders for application/json ContentType.
type PostApiV1MeProvidersJSONRequestBody = CreateProviderRequest

// PostApiV1OrgBookingsJSONRequestBody defines body for PostApiV1OrgBookings for application/json ContentType.
type PostApiV1OrgBookingsJSONRequestBody PostApiV1OrgBookingsJSONBody

// PostApiV1OrgBookingsBookingIdCancelJSONRequestBody defines body for PostApiV1OrgBookingsBookingIdCancel for application/json ContentType.
type PostApiV1OrgBookingsBookingIdCancelJSONRequestBody PostApiV1OrgBookingsBookingIdCancelJSONBody

// PostApiV1OrgBusinessHoursJSONRequestBody defines body for PostApiV1OrgBusinessHours for application/json ContentType.
type PostApiV1OrgBusinessHoursJSONRequestBody = CreateBusinessHoursRequest

// PutApiV1OrgBusinessHoursJSONRequestBody defines body for PutApiV1OrgBusinessHours for application/json ContentType.
type PutApiV1OrgBusinessHoursJSONRequestBody = ReplaceBusinessHoursRequest

// PatchApiV1OrgBusinessHoursHoursIdJSONRequestBody defines body for PatchApiV1OrgBusinessHoursHoursId for application/json ContentType.
type PatchApiV1OrgBusinessHoursHoursIdJSONRequestBody PatchApiV1OrgBusinessHoursHoursIdJSONBody

// PostApiV1OrgInvitationsJSONRequestBody defines body for PostApiV1OrgInvitations for application/json ContentType.
type PostApiV1OrgInvitationsJSONRequestBody PostApiV1OrgInvitationsJSONBody

// PostApiV1OrgMembersJSONRequestBody defines body for PostApiV1OrgMembers for application/json ContentType.
type PostApiV1OrgMembersJSONRequestBody PostApiV1OrgMembersJSONBody

// PatchApiV1OrgMembersUserIdJSONRequestBody defines body for PatchApiV1OrgMembersUserId for application/json ContentType.
type PatchApiV1OrgMembersUserIdJSONRequestBody PatchApiV1OrgMembersUserIdJSONBody

// PatchApiV1OrgProfileJSONRequestBody defines body for PatchApiV1OrgProfile for application/json ContentType.
type PatchApiV1OrgProfileJSONRequestBody = UpdateProviderRequest

// PutApiV1OrgProfileImagesKindMultipartRequestBody defines body for PutApiV1OrgProfileImagesKind for multipart/form-data ContentType.
type PutApiV1OrgProfileImagesKindMultipartRequestBody PutApiV1OrgProfileImagesKindMultipartBody

// PostApiV1OrgResourcesJSONRequestBody defines body for PostApiV1OrgResources for application/json ContentType.
type PostApiV1OrgResourcesJSONRequestBody = CreateResourceRequest

// PatchApiV1OrgResourcesResourceIdJSONRequestBody defines body for PatchApiV1OrgResourcesResourceId for application/json ContentType.
type PatchApiV1OrgResourcesResourceIdJSONRequestBody PatchApiV1OrgResourcesResourceIdJSONBody

// PostApiV1OrgScheduleExceptionsJSONRequestBody defines body for PostApiV1OrgScheduleExceptions for application/json ContentType.
type PostApiV1OrgScheduleExceptionsJSONRequestBody = CreateScheduleExceptionRequest

// PostApiV1OrgServicesJSONRequestBody defines body for PostApiV1OrgServices for application/json ContentType.
type PostApiV1OrgServicesJSONRequestBody = CreateServiceRequest

// PatchApiV1OrgServicesServiceIdJSONRequestBody defines body for PatchApiV1OrgServicesServiceId for application/json ContentType.
type PatchApiV1OrgServicesServiceIdJSONRequestBody = UpdateServiceRequest

// PostApiV1OrgServicesServiceIdMediaMultipartRequestBody defines body for PostApiV1OrgServicesServiceIdMedia for multipart/form-data ContentType.
type PostApiV1OrgServicesServiceIdMediaMultipartRequestBody PostApiV1OrgServicesServiceIdMediaMultipartBody

// PatchApiV1OrgServicesServiceIdMediaMediaIdJSONRequestBody defines body for PatchApiV1OrgServicesServiceIdMediaMediaId for application/json ContentType.
type PatchApiV1OrgServicesServiceIdMediaMediaIdJSONRequestBody PatchApiV1OrgServicesServiceIdMediaMediaIdJSONBody

// PostApiV1OrgServicesServiceIdOptionGroupsJSONRequestBody defines body for PostApiV1OrgServicesServiceIdOptionGroups for application/json ContentType.
type PostApiV1OrgServicesServiceIdOptionGroupsJSONRequestBody = CreateOptionGroupRequest

// PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdJSONRequestBody defines body for PatchApiV1OrgServicesServiceIdOptionGroupsGroupId for application/json ContentType.
type PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdJSONRequestBody = CreateOptionGroupRequest

// PostApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsJSONRequestBody defines body for PostApiV1OrgServicesServiceIdOptionGroupsGroupIdOptions for application/json ContentType.
type PostApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsJSONRequestBody = CreateOptionRequest

// PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionIdJSONRequestBody defines body for PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionId for application/json ContentType.
type PatchApiV1OrgServicesServiceIdOptionGroupsGroupIdOptionsOptionIdJSONRequestBody = CreateOptionRequest
