// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addBookingOption = `-- name: AddBookingOption :exec
INSERT INTO booking_options (booking_id, option_id, name, price_delta_cents, duration_delta_minutes, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
`

type AddBookingOptionParams struct {
	BookingID            uuid.UUID
	OptionID             *uuid.UUID
	Name                 string
	PriceDeltaCents      int32
	DurationDeltaMinutes int32
	SortOrder            int32
}

func (q *Queries) AddBookingOption(ctx context.Context, arg AddBookingOptionParams) error {
	_, err := q.db.Exec(ctx, addBookingOption,
		arg.BookingID,
		arg.OptionID,
		arg.Name,
		arg.PriceDeltaCents,
		arg.DurationDeltaMinutes,
		arg.SortOrder,
	)
	return err
}

const bookingCodeExists = `-- name: BookingCodeExists :one
SELECT EXISTS (SELECT 1 FROM bookings WHERE code = $1)
`

func (q *Queries) BookingCodeExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, bookingCodeExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAllBookings = `-- name: CountAllBookings :one
SELECT count(*) FROM bookings b
WHERE ($1::text = '' OR b.status = $1)
  AND ($2::uuid IS NULL OR b.provider_id = $2)
`

type CountAllBookingsParams struct {
	Status     string
	ProviderID *uuid.UUID
}

func (q *Queries) CountAllBookings(ctx context.Context, arg CountAllBookingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAllBookings, arg.Status, arg.ProviderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByCustomer = `-- name: CountBookingsByCustomer :one
SELECT count(*) FROM bookings
WHERE customer_id = $1 AND ($2::text = '' OR status = $2)
`

type CountBookingsByCustomerParams struct {
	CustomerID *uuid.UUID
	Status     string
}

func (q *Queries) CountBookingsByCustomer(ctx context.Context, arg CountBookingsByCustomerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByCustomer, arg.CustomerID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByProvider = `-- name: CountBookingsByProvider :one
SELECT count(*) FROM bookings b
WHERE b.provider_id = $1
  AND ($2::text = '' OR b.status = $2)
  AND ($3::uuid IS NULL OR b.resource_id = $3)
  AND ($4::timestamptz IS NULL OR b.starts_at >= $4)
  AND ($5::timestamptz IS NULL OR b.starts_at < $5)
`

type CountBookingsByProviderParams struct {
	ProviderID uuid.UUID
	Status     string
	ResourceID *uuid.UUID
	FromTime   *time.Time
	ToTime     *time.Time
}

func (q *Queries) CountBookingsByProvider(ctx context.Context, arg CountBookingsByProviderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBookingsByProvider,
		arg.ProviderID,
		arg.Status,
		arg.ResourceID,
		arg.FromTime,
		arg.ToTime,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    code, provider_id, service_id, resource_id, customer_id,
    starts_at, ends_at, status,
    service_name, price_cents, currency, duration_minutes, attributes,
    customer_note, customer_name, customer_phone
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12, $13,
    $14, $15, $16
)
RETURNING id, code, provider_id, service_id, resource_id, customer_id,
          starts_at, ends_at, status, service_name, price_cents, currency,
          duration_minutes, attributes, customer_note, customer_name,
          customer_phone, cancelled_by, cancel_reason, created_at, updated_at
`

type CreateBookingParams struct {
	Code            string
	ProviderID      uuid.UUID
	ServiceID       *uuid.UUID
	ResourceID      uuid.UUID
	CustomerID      *uuid.UUID
	StartsAt        time.Time
	EndsAt          time.Time
	Status          string
	ServiceName     string
	PriceCents      int32
	Currency        string
	DurationMinutes int32
	Attributes      []byte
	CustomerNote    *string
	CustomerName    *string
	CustomerPhone   *string
}

// May fail with 23P01 (bookings_no_overlap). The store maps that to SLOT_TAKEN.
func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.Code,
		arg.ProviderID,
		arg.ServiceID,
		arg.ResourceID,
		arg.CustomerID,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.ServiceName,
		arg.PriceCents,
		arg.Currency,
		arg.DurationMinutes,
		arg.Attributes,
		arg.CustomerNote,
		arg.CustomerName,
		arg.CustomerPhone,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProviderID,
		&i.ServiceID,
		&i.ResourceID,
		&i.CustomerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ServiceName,
		&i.PriceCents,
		&i.Currency,
		&i.DurationMinutes,
		&i.Attributes,
		&i.CustomerNote,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, code, provider_id, service_id, resource_id, customer_id,
       starts_at, ends_at, status, service_name, price_cents, currency,
       duration_minutes, attributes, customer_note, customer_name,
       customer_phone, cancelled_by, cancel_reason, created_at, updated_at
FROM bookings
WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProviderID,
		&i.ServiceID,
		&i.ResourceID,
		&i.CustomerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ServiceName,
		&i.PriceCents,
		&i.Currency,
		&i.DurationMinutes,
		&i.Attributes,
		&i.CustomerNote,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllBookings = `-- name: ListAllBookings :many
SELECT b.id, b.code, b.provider_id, b.service_id, b.resource_id, b.customer_id,
       b.starts_at, b.ends_at, b.status, b.service_name, b.price_cents, b.currency,
       b.duration_minutes, b.created_at, b.updated_at,
       p.slug AS provider_slug, p.name AS provider_name,
       u.name AS customer_user_name, u.email AS customer_user_email
FROM bookings b
JOIN providers p ON p.id = b.provider_id
LEFT JOIN users u ON u.id = b.customer_id
WHERE ($1::text = '' OR b.status = $1)
  AND ($2::uuid IS NULL OR b.provider_id = $2)
ORDER BY b.starts_at DESC
LIMIT $4 OFFSET $3
`

type ListAllBookingsParams struct {
	Status       string
	ProviderID   *uuid.UUID
	ResultOffset int32
	ResultLimit  int32
}

type ListAllBookingsRow struct {
	ID                uuid.UUID
	Code              string
	ProviderID        uuid.UUID
	ServiceID         *uuid.UUID
	ResourceID        uuid.UUID
	CustomerID        *uuid.UUID
	StartsAt          time.Time
	EndsAt            time.Time
	Status            string
	ServiceName       string
	PriceCents        int32
	Currency          string
	DurationMinutes   int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ProviderSlug      string
	ProviderName      string
	CustomerUserName  *string
	CustomerUserEmail *string
}

// Platform-admin cross-tenant listing. Deliberately separate from the
// provider inbox query: it is not org-scoped, so it must never share a code
// path with one that is.
func (q *Queries) ListAllBookings(ctx context.Context, arg ListAllBookingsParams) ([]ListAllBookingsRow, error) {
	rows, err := q.db.Query(ctx, listAllBookings,
		arg.Status,
		arg.ProviderID,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllBookingsRow{}
	for rows.Next() {
		var i ListAllBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ProviderID,
			&i.ServiceID,
			&i.ResourceID,
			&i.CustomerID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.ServiceName,
			&i.PriceCents,
			&i.Currency,
			&i.DurationMinutes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderSlug,
			&i.ProviderName,
			&i.CustomerUserName,
			&i.CustomerUserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingOptions = `-- name: ListBookingOptions :many
SELECT booking_id, option_id, name, price_delta_cents, duration_delta_minutes, sort_order
FROM booking_options
WHERE booking_id = ANY ($1::uuid[])
ORDER BY booking_id, sort_order
`

func (q *Queries) ListBookingOptions(ctx context.Context, bookingIds []uuid.UUID) ([]BookingOption, error) {
	rows, err := q.db.Query(ctx, listBookingOptions, bookingIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookingOption{}
	for rows.Next() {
		var i BookingOption
		if err := rows.Scan(
			&i.BookingID,
			&i.OptionID,
			&i.Name,
			&i.PriceDeltaCents,
			&i.DurationDeltaMinutes,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByCustomer = `-- name: ListBookingsByCustomer :many
SELECT b.id, b.code, b.provider_id, b.service_id, b.resource_id, b.customer_id,
       b.starts_at, b.ends_at, b.status, b.service_name, b.price_cents, b.currency,
       b.duration_minutes, b.attributes, b.customer_note, b.cancelled_by,
       b.cancel_reason, b.created_at, b.updated_at,
       p.slug AS provider_slug, p.name AS provider_name, p.logo_url AS provider_logo_url,
       p.city AS provider_city, p.timezone AS provider_timezone
FROM bookings b
JOIN providers p ON p.id = b.provider_id
WHERE b.customer_id = $1
  AND ($2::text = '' OR b.status = $2)
ORDER BY b.starts_at DESC
LIMIT $4 OFFSET $3
`

type ListBookingsByCustomerParams struct {
	CustomerID   *uuid.UUID
	Status       string
	ResultOffset int32
	ResultLimit  int32
}

type ListBookingsByCustomerRow struct {
	ID               uuid.UUID
	Code             string
	ProviderID       uuid.UUID
	ServiceID        *uuid.UUID
	ResourceID       uuid.UUID
	CustomerID       *uuid.UUID
	StartsAt         time.Time
	EndsAt           time.Time
	Status           string
	ServiceName      string
	PriceCents       int32
	Currency         string
	DurationMinutes  int32
	Attributes       []byte
	CustomerNote     *string
	CancelledBy      *string
	CancelReason     *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ProviderSlug     string
	ProviderName     string
	ProviderLogoUrl  *string
	ProviderCity     *string
	ProviderTimezone string
}

func (q *Queries) ListBookingsByCustomer(ctx context.Context, arg ListBookingsByCustomerParams) ([]ListBookingsByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByCustomer,
		arg.CustomerID,
		arg.Status,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByCustomerRow{}
	for rows.Next() {
		var i ListBookingsByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ProviderID,
			&i.ServiceID,
			&i.ResourceID,
			&i.CustomerID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.ServiceName,
			&i.PriceCents,
			&i.Currency,
			&i.DurationMinutes,
			&i.Attributes,
			&i.CustomerNote,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProviderSlug,
			&i.ProviderName,
			&i.ProviderLogoUrl,
			&i.ProviderCity,
			&i.ProviderTimezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByProvider = `-- name: ListBookingsByProvider :many
SELECT b.id, b.code, b.provider_id, b.service_id, b.resource_id, b.customer_id,
       b.starts_at, b.ends_at, b.status, b.service_name, b.price_cents, b.currency,
       b.duration_minutes, b.attributes, b.customer_note, b.customer_name,
       b.customer_phone, b.cancelled_by, b.cancel_reason, b.created_at, b.updated_at,
       r.name AS resource_name,
       u.name AS customer_user_name, u.phone AS customer_user_phone
FROM bookings b
JOIN resources r ON r.id = b.resource_id
LEFT JOIN users u ON u.id = b.customer_id
WHERE b.provider_id = $1
  AND ($2::text = '' OR b.status = $2)
  AND ($3::uuid IS NULL OR b.resource_id = $3)
  AND ($4::timestamptz IS NULL OR b.starts_at >= $4)
  AND ($5::timestamptz IS NULL OR b.starts_at < $5)
ORDER BY b.starts_at
LIMIT $7 OFFSET $6
`

type ListBookingsByProviderParams struct {
	ProviderID   uuid.UUID
	Status       string
	ResourceID   *uuid.UUID
	FromTime     *time.Time
	ToTime       *time.Time
	ResultOffset int32
	ResultLimit  int32
}

type ListBookingsByProviderRow struct {
	ID                uuid.UUID
	Code              string
	ProviderID        uuid.UUID
	ServiceID         *uuid.UUID
	ResourceID        uuid.UUID
	CustomerID        *uuid.UUID
	StartsAt          time.Time
	EndsAt            time.Time
	Status            string
	ServiceName       string
	PriceCents        int32
	Currency          string
	DurationMinutes   int32
	Attributes        []byte
	CustomerNote      *string
	CustomerName      *string
	CustomerPhone     *string
	CancelledBy       *string
	CancelReason      *string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ResourceName      string
	CustomerUserName  *string
	CustomerUserPhone *string
}

// The provider's inbox: a day at a time, optionally narrowed to one resource.
func (q *Queries) ListBookingsByProvider(ctx context.Context, arg ListBookingsByProviderParams) ([]ListBookingsByProviderRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByProvider,
		arg.ProviderID,
		arg.Status,
		arg.ResourceID,
		arg.FromTime,
		arg.ToTime,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByProviderRow{}
	for rows.Next() {
		var i ListBookingsByProviderRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.ProviderID,
			&i.ServiceID,
			&i.ResourceID,
			&i.CustomerID,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.ServiceName,
			&i.PriceCents,
			&i.Currency,
			&i.DurationMinutes,
			&i.Attributes,
			&i.CustomerNote,
			&i.CustomerName,
			&i.CustomerPhone,
			&i.CancelledBy,
			&i.CancelReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResourceName,
			&i.CustomerUserName,
			&i.CustomerUserPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusyIntervals = `-- name: ListBusyIntervals :many
SELECT resource_id, starts_at, ends_at
FROM bookings
WHERE resource_id = ANY ($1::uuid[])
  AND status IN ('pending', 'confirmed', 'in_progress')
  AND starts_at < $2
  AND ends_at > $3
ORDER BY resource_id, starts_at
`

type ListBusyIntervalsParams struct {
	ResourceIds []uuid.UUID
	WindowEnd   time.Time
	WindowStart time.Time
}

type ListBusyIntervalsRow struct {
	ResourceID uuid.UUID
	StartsAt   time.Time
	EndsAt     time.Time
}

// Availability step 3: what already occupies these resources in this window.
func (q *Queries) ListBusyIntervals(ctx context.Context, arg ListBusyIntervalsParams) ([]ListBusyIntervalsRow, error) {
	rows, err := q.db.Query(ctx, listBusyIntervals, arg.ResourceIds, arg.WindowEnd, arg.WindowStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusyIntervalsRow{}
	for rows.Next() {
		var i ListBusyIntervalsRow
		if err := rows.Scan(&i.ResourceID, &i.StartsAt, &i.EndsAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerBookingStats = `-- name: ProviderBookingStats :one
SELECT
    count(*) FILTER (WHERE status = 'pending')                     AS pending_count,
    count(*) FILTER (WHERE status = 'confirmed')                   AS confirmed_count,
    count(*) FILTER (WHERE status = 'in_progress')                 AS in_progress_count,
    count(*) FILTER (WHERE status = 'completed')                   AS completed_count,
    count(*) FILTER (WHERE status IN ('cancelled_by_customer', 'cancelled_by_provider'))
                                                                   AS cancelled_count,
    count(*) FILTER (WHERE status = 'no_show')                     AS no_show_count,
    COALESCE(sum(price_cents) FILTER (WHERE status = 'completed'), 0)::bigint
                                                                   AS completed_revenue_cents
FROM bookings
WHERE provider_id = $1
  AND ($2::timestamptz IS NULL OR starts_at >= $2)
  AND ($3::timestamptz IS NULL OR starts_at < $3)
`

type ProviderBookingStatsParams struct {
	ProviderID uuid.UUID
	FromTime   *time.Time
	ToTime     *time.Time
}

type ProviderBookingStatsRow struct {
	PendingCount          int64
	ConfirmedCount        int64
	InProgressCount       int64
	CompletedCount        int64
	CancelledCount        int64
	NoShowCount           int64
	CompletedRevenueCents int64
}

func (q *Queries) ProviderBookingStats(ctx context.Context, arg ProviderBookingStatsParams) (ProviderBookingStatsRow, error) {
	row := q.db.QueryRow(ctx, providerBookingStats, arg.ProviderID, arg.FromTime, arg.ToTime)
	var i ProviderBookingStatsRow
	err := row.Scan(
		&i.PendingCount,
		&i.ConfirmedCount,
		&i.InProgressCount,
		&i.CompletedCount,
		&i.CancelledCount,
		&i.NoShowCount,
		&i.CompletedRevenueCents,
	)
	return i, err
}

const transitionBooking = `-- name: TransitionBooking :one
UPDATE bookings
SET status        = $1,
    cancelled_by  = $2,
    cancel_reason = $3,
    updated_at    = now()
WHERE id = $4 AND status = $5
RETURNING id, code, provider_id, service_id, resource_id, customer_id,
          starts_at, ends_at, status, service_name, price_cents, currency,
          duration_minutes, attributes, customer_note, customer_name,
          customer_phone, cancelled_by, cancel_reason, created_at, updated_at
`

type TransitionBookingParams struct {
	ToStatus     string
	CancelledBy  *string
	CancelReason *string
	ID           uuid.UUID
	FromStatus   string
}

// The state machine writes through here. The `from_status` guard makes the
// transition atomic: a concurrent update leaves this returning no rows.
func (q *Queries) TransitionBooking(ctx context.Context, arg TransitionBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, transitionBooking,
		arg.ToStatus,
		arg.CancelledBy,
		arg.CancelReason,
		arg.ID,
		arg.FromStatus,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.ProviderID,
		&i.ServiceID,
		&i.ResourceID,
		&i.CustomerID,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.ServiceName,
		&i.PriceCents,
		&i.Currency,
		&i.DurationMinutes,
		&i.Attributes,
		&i.CustomerNote,
		&i.CustomerName,
		&i.CustomerPhone,
		&i.CancelledBy,
		&i.CancelReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
