// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addProviderCategory = `-- name: AddProviderCategory :exec

INSERT INTO provider_categories (provider_id, category_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddProviderCategoryParams struct {
	ProviderID uuid.UUID
	CategoryID uuid.UUID
}

// ---------------------------------------------------------------- provider_categories
func (q *Queries) AddProviderCategory(ctx context.Context, arg AddProviderCategoryParams) error {
	_, err := q.db.Exec(ctx, addProviderCategory, arg.ProviderID, arg.CategoryID)
	return err
}

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (slug, name, icon, parent_id, sort_order, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, slug, name, icon, parent_id, sort_order, is_active, created_at, updated_at
`

type CreateCategoryParams struct {
	Slug      string
	Name      string
	Icon      *string
	ParentID  *uuid.UUID
	SortOrder int32
	IsActive  bool
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory,
		arg.Slug,
		arg.Name,
		arg.Icon,
		arg.ParentID,
		arg.SortOrder,
		arg.IsActive,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, slug, name, icon, parent_id, sort_order, is_active, created_at, updated_at
FROM categories
WHERE id = $1
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategoryBySlug = `-- name: GetCategoryBySlug :one
SELECT id, slug, name, icon, parent_id, sort_order, is_active, created_at, updated_at
FROM categories
WHERE slug = $1
`

func (q *Queries) GetCategoryBySlug(ctx context.Context, slug string) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryBySlug, slug)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name, icon, parent_id, sort_order, is_active, created_at, updated_at
FROM categories
WHERE ($1::bool = false OR is_active)
ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context, activeOnly bool) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories, activeOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Icon,
			&i.ParentID,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderCategories = `-- name: ListProviderCategories :many
SELECT c.id, c.slug, c.name, c.icon, c.parent_id, c.sort_order, c.is_active
FROM provider_categories pc
JOIN categories c ON c.id = pc.category_id
WHERE pc.provider_id = $1
ORDER BY c.sort_order, c.name
`

type ListProviderCategoriesRow struct {
	ID        uuid.UUID
	Slug      string
	Name      string
	Icon      *string
	ParentID  *uuid.UUID
	SortOrder int32
	IsActive  bool
}

func (q *Queries) ListProviderCategories(ctx context.Context, providerID uuid.UUID) ([]ListProviderCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listProviderCategories, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProviderCategoriesRow{}
	for rows.Next() {
		var i ListProviderCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Icon,
			&i.ParentID,
			&i.SortOrder,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProviderCategory = `-- name: RemoveProviderCategory :execrows
DELETE FROM provider_categories
WHERE provider_id = $1 AND category_id = $2
`

type RemoveProviderCategoryParams struct {
	ProviderID uuid.UUID
	CategoryID uuid.UUID
}

func (q *Queries) RemoveProviderCategory(ctx context.Context, arg RemoveProviderCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeProviderCategory, arg.ProviderID, arg.CategoryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceProviderCategories = `-- name: ReplaceProviderCategories :exec
WITH deleted AS (
    DELETE FROM provider_categories
    WHERE provider_id = $1
      AND category_id <> ALL ($2::uuid[])
)
INSERT INTO provider_categories (provider_id, category_id)
SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type ReplaceProviderCategoriesParams struct {
	ProviderID  uuid.UUID
	CategoryIds []uuid.UUID
}

func (q *Queries) ReplaceProviderCategories(ctx context.Context, arg ReplaceProviderCategoriesParams) error {
	_, err := q.db.Exec(ctx, replaceProviderCategories, arg.ProviderID, arg.CategoryIds)
	return err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET slug       = COALESCE($1, slug),
    name       = COALESCE($2, name),
    icon       = COALESCE($3, icon),
    parent_id  = COALESCE($4, parent_id),
    sort_order = COALESCE($5, sort_order),
    is_active  = COALESCE($6, is_active),
    updated_at = now()
WHERE id = $7
RETURNING id, slug, name, icon, parent_id, sort_order, is_active, created_at, updated_at
`

type UpdateCategoryParams struct {
	Slug      *string
	Name      *string
	Icon      *string
	ParentID  *uuid.UUID
	SortOrder *int32
	IsActive  *bool
	ID        uuid.UUID
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory,
		arg.Slug,
		arg.Name,
		arg.Icon,
		arg.ParentID,
		arg.SortOrder,
		arg.IsActive,
		arg.ID,
	)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Icon,
		&i.ParentID,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
