// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: category_attributes.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCategoryAttribute = `-- name: CreateCategoryAttribute :one
INSERT INTO category_attributes (
    category_id, key, label, data_type, options, required, applies_to, filterable, sort_order
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9
)
RETURNING id, category_id, key, label, data_type, options, required, applies_to,
          filterable, sort_order, created_at, updated_at
`

type CreateCategoryAttributeParams struct {
	CategoryID uuid.UUID
	Key        string
	Label      string
	DataType   string
	Options    []byte
	Required   bool
	AppliesTo  string
	Filterable bool
	SortOrder  int32
}

func (q *Queries) CreateCategoryAttribute(ctx context.Context, arg CreateCategoryAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, createCategoryAttribute,
		arg.CategoryID,
		arg.Key,
		arg.Label,
		arg.DataType,
		arg.Options,
		arg.Required,
		arg.AppliesTo,
		arg.Filterable,
		arg.SortOrder,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Key,
		&i.Label,
		&i.DataType,
		&i.Options,
		&i.Required,
		&i.AppliesTo,
		&i.Filterable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCategoryAttribute = `-- name: DeleteCategoryAttribute :execrows
DELETE FROM category_attributes WHERE id = $1
`

func (q *Queries) DeleteCategoryAttribute(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategoryAttribute, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategoryAttribute = `-- name: GetCategoryAttribute :one
SELECT id, category_id, key, label, data_type, options, required, applies_to,
       filterable, sort_order, created_at, updated_at
FROM category_attributes
WHERE id = $1
`

func (q *Queries) GetCategoryAttribute(ctx context.Context, id uuid.UUID) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, getCategoryAttribute, id)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Key,
		&i.Label,
		&i.DataType,
		&i.Options,
		&i.Required,
		&i.AppliesTo,
		&i.Filterable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategoryAttributes = `-- name: ListCategoryAttributes :many
SELECT id, category_id, key, label, data_type, options, required, applies_to,
       filterable, sort_order, created_at, updated_at
FROM category_attributes
WHERE category_id = $1
  AND ($2::text = '' OR applies_to = $2)
ORDER BY sort_order, key
`

type ListCategoryAttributesParams struct {
	CategoryID uuid.UUID
	AppliesTo  string
}

// Drives the dynamic forms on both clients, and the validator on every write.
func (q *Queries) ListCategoryAttributes(ctx context.Context, arg ListCategoryAttributesParams) ([]CategoryAttribute, error) {
	rows, err := q.db.Query(ctx, listCategoryAttributes, arg.CategoryID, arg.AppliesTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryAttribute{}
	for rows.Next() {
		var i CategoryAttribute
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Key,
			&i.Label,
			&i.DataType,
			&i.Options,
			&i.Required,
			&i.AppliesTo,
			&i.Filterable,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilterableAttributes = `-- name: ListFilterableAttributes :many
SELECT id, category_id, key, label, data_type, options, required, applies_to,
       filterable, sort_order
FROM category_attributes
WHERE category_id = $1 AND filterable
ORDER BY sort_order, key
`

type ListFilterableAttributesRow struct {
	ID         uuid.UUID
	CategoryID uuid.UUID
	Key        string
	Label      string
	DataType   string
	Options    []byte
	Required   bool
	AppliesTo  string
	Filterable bool
	SortOrder  int32
}

// discovery/filter.go builds its jsonb containment filter from these, never
// from raw query params.
func (q *Queries) ListFilterableAttributes(ctx context.Context, categoryID uuid.UUID) ([]ListFilterableAttributesRow, error) {
	rows, err := q.db.Query(ctx, listFilterableAttributes, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilterableAttributesRow{}
	for rows.Next() {
		var i ListFilterableAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Key,
			&i.Label,
			&i.DataType,
			&i.Options,
			&i.Required,
			&i.AppliesTo,
			&i.Filterable,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategoryAttribute = `-- name: UpdateCategoryAttribute :one
UPDATE category_attributes
SET label      = COALESCE($1, label),
    data_type  = COALESCE($2, data_type),
    options    = COALESCE($3, options),
    required   = COALESCE($4, required),
    filterable = COALESCE($5, filterable),
    sort_order = COALESCE($6, sort_order),
    updated_at = now()
WHERE id = $7
RETURNING id, category_id, key, label, data_type, options, required, applies_to,
          filterable, sort_order, created_at, updated_at
`

type UpdateCategoryAttributeParams struct {
	Label      *string
	DataType   *string
	Options    []byte
	Required   *bool
	Filterable *bool
	SortOrder  *int32
	ID         uuid.UUID
}

func (q *Queries) UpdateCategoryAttribute(ctx context.Context, arg UpdateCategoryAttributeParams) (CategoryAttribute, error) {
	row := q.db.QueryRow(ctx, updateCategoryAttribute,
		arg.Label,
		arg.DataType,
		arg.Options,
		arg.Required,
		arg.Filterable,
		arg.SortOrder,
		arg.ID,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Key,
		&i.Label,
		&i.DataType,
		&i.Options,
		&i.Required,
		&i.AppliesTo,
		&i.Filterable,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
