// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE invitations
SET accepted_at = now()
WHERE id = $1 AND accepted_at IS NULL AND expires_at > now()
RETURNING id, provider_id, email, role, expires_at, accepted_at, created_at
`

type AcceptInvitationRow struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
	Email      string
	Role       string
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	CreatedAt  time.Time
}

func (q *Queries) AcceptInvitation(ctx context.Context, id uuid.UUID) (AcceptInvitationRow, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, id)
	var i AcceptInvitationRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO invitations (provider_id, email, role, token_hash, expires_at)
VALUES ($1, lower($2), $3, $4, $5)
RETURNING id, provider_id, email, role, expires_at, accepted_at, created_at
`

type CreateInvitationParams struct {
	ProviderID uuid.UUID
	Email      string
	Role       string
	TokenHash  string
	ExpiresAt  time.Time
}

type CreateInvitationRow struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
	Email      string
	Role       string
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	CreatedAt  time.Time
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.ProviderID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i CreateInvitationRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Email,
		&i.Role,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvitation = `-- name: DeleteInvitation :execrows
DELETE FROM invitations
WHERE id = $1 AND provider_id = $2 AND accepted_at IS NULL
`

type DeleteInvitationParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteInvitation, arg.ID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getInvitationByTokenHash = `-- name: GetInvitationByTokenHash :one
SELECT id, provider_id, email, role, token_hash, expires_at, accepted_at, created_at
FROM invitations
WHERE token_hash = $1
`

func (q *Queries) GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getInvitationByTokenHash, tokenHash)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listInvitations = `-- name: ListInvitations :many
SELECT id, provider_id, email, role, expires_at, accepted_at, created_at
FROM invitations
WHERE provider_id = $1
ORDER BY created_at DESC
`

type ListInvitationsRow struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
	Email      string
	Role       string
	ExpiresAt  time.Time
	AcceptedAt *time.Time
	CreatedAt  time.Time
}

func (q *Queries) ListInvitations(ctx context.Context, providerID uuid.UUID) ([]ListInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listInvitations, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitationsRow{}
	for rows.Next() {
		var i ListInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Email,
			&i.Role,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
