// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :one
INSERT INTO members (provider_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (provider_id, user_id) DO UPDATE SET role = EXCLUDED.role
RETURNING provider_id, user_id, role, created_at
`

type AddMemberParams struct {
	ProviderID uuid.UUID
	UserID     uuid.UUID
	Role       string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, addMember, arg.ProviderID, arg.UserID, arg.Role)
	var i Member
	err := row.Scan(
		&i.ProviderID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const countOwners = `-- name: CountOwners :one
SELECT count(*) FROM members
WHERE provider_id = $1 AND role = 'owner'
`

// Guards against removing or demoting the last owner of a provider.
func (q *Queries) CountOwners(ctx context.Context, providerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwners, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMembership = `-- name: GetMembership :one
SELECT provider_id, user_id, role, created_at
FROM members
WHERE provider_id = $1 AND user_id = $2
`

type GetMembershipParams struct {
	ProviderID uuid.UUID
	UserID     uuid.UUID
}

// The membership check behind every /org/* request. `x-organization-id` is
// client-supplied, so this runs before any org-scoped data is read.
func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.ProviderID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ProviderID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listMembers = `-- name: ListMembers :many
SELECT m.provider_id, m.user_id, m.role, m.created_at,
       u.name, u.email, u.phone
FROM members m
JOIN users u ON u.id = m.user_id
WHERE m.provider_id = $1
ORDER BY
    CASE m.role WHEN 'owner' THEN 0 WHEN 'admin' THEN 1 ELSE 2 END,
    u.name
`

type ListMembersRow struct {
	ProviderID uuid.UUID
	UserID     uuid.UUID
	Role       string
	CreatedAt  time.Time
	Name       string
	Email      string
	Phone      *string
}

func (q *Queries) ListMembers(ctx context.Context, providerID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.Name,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembershipsByUser = `-- name: ListMembershipsByUser :many
SELECT m.provider_id, m.role, p.slug, p.name, p.status
FROM members m
JOIN providers p ON p.id = m.provider_id
WHERE m.user_id = $1
ORDER BY p.name
`

type ListMembershipsByUserRow struct {
	ProviderID uuid.UUID
	Role       string
	Slug       string
	Name       string
	Status     string
}

// Feeds the JWT `memberships` claim at sign-in and refresh.
func (q *Queries) ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error) {
	rows, err := q.db.Query(ctx, listMembershipsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembershipsByUserRow{}
	for rows.Next() {
		var i ListMembershipsByUserRow
		if err := rows.Scan(
			&i.ProviderID,
			&i.Role,
			&i.Slug,
			&i.Name,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM members
WHERE provider_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	ProviderID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.ProviderID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberRole = `-- name: UpdateMemberRole :one
UPDATE members
SET role = $1
WHERE provider_id = $2 AND user_id = $3
RETURNING provider_id, user_id, role, created_at
`

type UpdateMemberRoleParams struct {
	Role       string
	ProviderID uuid.UUID
	UserID     uuid.UUID
}

func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberRole, arg.Role, arg.ProviderID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ProviderID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
