// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: options.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOptionGroup = `-- name: CreateOptionGroup :one
INSERT INTO option_groups (service_id, name, selection_type, is_required, min_select, max_select, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, service_id, name, selection_type, is_required, min_select, max_select,
          sort_order, created_at, updated_at
`

type CreateOptionGroupParams struct {
	ServiceID     uuid.UUID
	Name          string
	SelectionType string
	IsRequired    bool
	MinSelect     int32
	MaxSelect     *int32
	SortOrder     int32
}

func (q *Queries) CreateOptionGroup(ctx context.Context, arg CreateOptionGroupParams) (OptionGroup, error) {
	row := q.db.QueryRow(ctx, createOptionGroup,
		arg.ServiceID,
		arg.Name,
		arg.SelectionType,
		arg.IsRequired,
		arg.MinSelect,
		arg.MaxSelect,
		arg.SortOrder,
	)
	var i OptionGroup
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.SelectionType,
		&i.IsRequired,
		&i.MinSelect,
		&i.MaxSelect,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createServiceOption = `-- name: CreateServiceOption :one

INSERT INTO service_options (group_id, name, price_delta_cents, duration_delta_minutes, is_active, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, group_id, name, price_delta_cents, duration_delta_minutes, is_active,
          sort_order, created_at, updated_at
`

type CreateServiceOptionParams struct {
	GroupID              uuid.UUID
	Name                 string
	PriceDeltaCents      int32
	DurationDeltaMinutes int32
	IsActive             bool
	SortOrder            int32
}

// ---------------------------------------------------------------- options
func (q *Queries) CreateServiceOption(ctx context.Context, arg CreateServiceOptionParams) (ServiceOption, error) {
	row := q.db.QueryRow(ctx, createServiceOption,
		arg.GroupID,
		arg.Name,
		arg.PriceDeltaCents,
		arg.DurationDeltaMinutes,
		arg.IsActive,
		arg.SortOrder,
	)
	var i ServiceOption
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.PriceDeltaCents,
		&i.DurationDeltaMinutes,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOptionGroup = `-- name: DeleteOptionGroup :execrows
DELETE FROM option_groups WHERE id = $1 AND service_id = $2
`

type DeleteOptionGroupParams struct {
	ID        uuid.UUID
	ServiceID uuid.UUID
}

func (q *Queries) DeleteOptionGroup(ctx context.Context, arg DeleteOptionGroupParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOptionGroup, arg.ID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServiceOption = `-- name: DeleteServiceOption :execrows
DELETE FROM service_options WHERE id = $1 AND group_id = $2
`

type DeleteServiceOptionParams struct {
	ID      uuid.UUID
	GroupID uuid.UUID
}

func (q *Queries) DeleteServiceOption(ctx context.Context, arg DeleteServiceOptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceOption, arg.ID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOptionGroup = `-- name: GetOptionGroup :one
SELECT id, service_id, name, selection_type, is_required, min_select, max_select,
       sort_order, created_at, updated_at
FROM option_groups
WHERE id = $1
`

func (q *Queries) GetOptionGroup(ctx context.Context, id uuid.UUID) (OptionGroup, error) {
	row := q.db.QueryRow(ctx, getOptionGroup, id)
	var i OptionGroup
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.SelectionType,
		&i.IsRequired,
		&i.MinSelect,
		&i.MaxSelect,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOptionGroupsByService = `-- name: ListOptionGroupsByService :many
SELECT id, service_id, name, selection_type, is_required, min_select, max_select,
       sort_order, created_at, updated_at
FROM option_groups
WHERE service_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListOptionGroupsByService(ctx context.Context, serviceID uuid.UUID) ([]OptionGroup, error) {
	rows, err := q.db.Query(ctx, listOptionGroupsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OptionGroup{}
	for rows.Next() {
		var i OptionGroup
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.Name,
			&i.SelectionType,
			&i.IsRequired,
			&i.MinSelect,
			&i.MaxSelect,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByGroup = `-- name: ListOptionsByGroup :many
SELECT id, group_id, name, price_delta_cents, duration_delta_minutes, is_active,
       sort_order, created_at, updated_at
FROM service_options
WHERE group_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListOptionsByGroup(ctx context.Context, groupID uuid.UUID) ([]ServiceOption, error) {
	rows, err := q.db.Query(ctx, listOptionsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceOption{}
	for rows.Next() {
		var i ServiceOption
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.PriceDeltaCents,
			&i.DurationDeltaMinutes,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByIDs = `-- name: ListOptionsByIDs :many
SELECT o.id, o.group_id, o.name, o.price_delta_cents, o.duration_delta_minutes,
       o.is_active, o.sort_order,
       g.service_id, g.name AS group_name, g.selection_type, g.is_required,
       g.min_select, g.max_select
FROM service_options o
JOIN option_groups g ON g.id = o.group_id
WHERE o.id = ANY ($1::uuid[])
ORDER BY g.sort_order, o.sort_order
`

type ListOptionsByIDsRow struct {
	ID                   uuid.UUID
	GroupID              uuid.UUID
	Name                 string
	PriceDeltaCents      int32
	DurationDeltaMinutes int32
	IsActive             bool
	SortOrder            int32
	ServiceID            uuid.UUID
	GroupName            string
	SelectionType        string
	IsRequired           bool
	MinSelect            int32
	MaxSelect            *int32
}

// The pricing query: given the option ids a client claims it picked, return
// what they actually are. Totals are recomputed from this, never trusted.
func (q *Queries) ListOptionsByIDs(ctx context.Context, ids []uuid.UUID) ([]ListOptionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, listOptionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionsByIDsRow{}
	for rows.Next() {
		var i ListOptionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.PriceDeltaCents,
			&i.DurationDeltaMinutes,
			&i.IsActive,
			&i.SortOrder,
			&i.ServiceID,
			&i.GroupName,
			&i.SelectionType,
			&i.IsRequired,
			&i.MinSelect,
			&i.MaxSelect,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionsByService = `-- name: ListOptionsByService :many
SELECT o.id, o.group_id, o.name, o.price_delta_cents, o.duration_delta_minutes,
       o.is_active, o.sort_order, o.created_at, o.updated_at
FROM service_options o
JOIN option_groups g ON g.id = o.group_id
WHERE g.service_id = $1
ORDER BY g.sort_order, o.sort_order, o.name
`

// One round trip for a service's whole option tree.
func (q *Queries) ListOptionsByService(ctx context.Context, serviceID uuid.UUID) ([]ServiceOption, error) {
	rows, err := q.db.Query(ctx, listOptionsByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceOption{}
	for rows.Next() {
		var i ServiceOption
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.PriceDeltaCents,
			&i.DurationDeltaMinutes,
			&i.IsActive,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOptionGroup = `-- name: UpdateOptionGroup :one
UPDATE option_groups
SET name           = COALESCE($1, name),
    selection_type = COALESCE($2, selection_type),
    is_required    = COALESCE($3, is_required),
    min_select     = COALESCE($4, min_select),
    max_select     = COALESCE($5, max_select),
    sort_order     = COALESCE($6, sort_order),
    updated_at     = now()
WHERE id = $7 AND service_id = $8
RETURNING id, service_id, name, selection_type, is_required, min_select, max_select,
          sort_order, created_at, updated_at
`

type UpdateOptionGroupParams struct {
	Name          *string
	SelectionType *string
	IsRequired    *bool
	MinSelect     *int32
	MaxSelect     *int32
	SortOrder     *int32
	ID            uuid.UUID
	ServiceID     uuid.UUID
}

func (q *Queries) UpdateOptionGroup(ctx context.Context, arg UpdateOptionGroupParams) (OptionGroup, error) {
	row := q.db.QueryRow(ctx, updateOptionGroup,
		arg.Name,
		arg.SelectionType,
		arg.IsRequired,
		arg.MinSelect,
		arg.MaxSelect,
		arg.SortOrder,
		arg.ID,
		arg.ServiceID,
	)
	var i OptionGroup
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.Name,
		&i.SelectionType,
		&i.IsRequired,
		&i.MinSelect,
		&i.MaxSelect,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateServiceOption = `-- name: UpdateServiceOption :one
UPDATE service_options
SET name                   = COALESCE($1, name),
    price_delta_cents      = COALESCE($2, price_delta_cents),
    duration_delta_minutes = COALESCE($3, duration_delta_minutes),
    is_active              = COALESCE($4, is_active),
    sort_order             = COALESCE($5, sort_order),
    updated_at             = now()
WHERE id = $6 AND group_id = $7
RETURNING id, group_id, name, price_delta_cents, duration_delta_minutes, is_active,
          sort_order, created_at, updated_at
`

type UpdateServiceOptionParams struct {
	Name                 *string
	PriceDeltaCents      *int32
	DurationDeltaMinutes *int32
	IsActive             *bool
	SortOrder            *int32
	ID                   uuid.UUID
	GroupID              uuid.UUID
}

func (q *Queries) UpdateServiceOption(ctx context.Context, arg UpdateServiceOptionParams) (ServiceOption, error) {
	row := q.db.QueryRow(ctx, updateServiceOption,
		arg.Name,
		arg.PriceDeltaCents,
		arg.DurationDeltaMinutes,
		arg.IsActive,
		arg.SortOrder,
		arg.ID,
		arg.GroupID,
	)
	var i ServiceOption
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Name,
		&i.PriceDeltaCents,
		&i.DurationDeltaMinutes,
		&i.IsActive,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
