// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: providers.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countProviders = `-- name: CountProviders :one
SELECT count(*) FROM providers
WHERE ($1::text = '' OR status = $1)
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%' OR slug ILIKE '%' || $2 || '%')
`

type CountProvidersParams struct {
	Status string
	Search string
}

func (q *Queries) CountProviders(ctx context.Context, arg CountProvidersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProviders, arg.Status, arg.Search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProvider = `-- name: CreateProvider :one

INSERT INTO providers (
    slug, name, phone, email, description, city, address, location,
    timezone, license_number, booking_mode, min_lead_minutes
)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7,
    CASE
        WHEN $8::float8 IS NULL OR $9::float8 IS NULL THEN NULL
        ELSE ST_SetSRID(ST_MakePoint($8::float8, $9::float8), 4326)::geography
    END,
    $10, $11, $12, $13
)
RETURNING
    id, slug, name, phone, email, description, city, address,
    (location IS NOT NULL)::bool AS has_location,
    COALESCE(ST_X(location::geometry), 0)::float8 AS lng,
    COALESCE(ST_Y(location::geometry), 0)::float8 AS lat,
    timezone, logo_url, logo_public_id, cover_url, cover_public_id,
    license_number, status,
    rating_avg::float8 AS rating_avg, rating_count, booking_mode,
    min_lead_minutes, created_at, updated_at
`

type CreateProviderParams struct {
	Slug           string
	Name           string
	Phone          *string
	Email          *string
	Description    *string
	City           *string
	Address        *string
	Lng            *float64
	Lat            *float64
	Timezone       string
	LicenseNumber  *string
	BookingMode    string
	MinLeadMinutes int32
}

type CreateProviderRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Phone          *string
	Email          *string
	Description    *string
	City           *string
	Address        *string
	HasLocation    bool
	Lng            float64
	Lat            float64
	Timezone       string
	LogoUrl        *string
	LogoPublicID   *string
	CoverUrl       *string
	CoverPublicID  *string
	LicenseNumber  *string
	Status         string
	RatingAvg      float64
	RatingCount    int32
	BookingMode    string
	MinLeadMinutes int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// The `location` column is a PostGIS geography, which sqlc has no Go mapping
// for. Every query therefore projects it as an explicit has_location/lng/lat
// triple and never selects the raw column.
func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (CreateProviderRow, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.Slug,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Description,
		arg.City,
		arg.Address,
		arg.Lng,
		arg.Lat,
		arg.Timezone,
		arg.LicenseNumber,
		arg.BookingMode,
		arg.MinLeadMinutes,
	)
	var i CreateProviderRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.City,
		&i.Address,
		&i.HasLocation,
		&i.Lng,
		&i.Lat,
		&i.Timezone,
		&i.LogoUrl,
		&i.LogoPublicID,
		&i.CoverUrl,
		&i.CoverPublicID,
		&i.LicenseNumber,
		&i.Status,
		&i.RatingAvg,
		&i.RatingCount,
		&i.BookingMode,
		&i.MinLeadMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT
    id, slug, name, phone, email, description, city, address,
    (location IS NOT NULL)::bool AS has_location,
    COALESCE(ST_X(location::geometry), 0)::float8 AS lng,
    COALESCE(ST_Y(location::geometry), 0)::float8 AS lat,
    timezone, logo_url, logo_public_id, cover_url, cover_public_id,
    license_number, status,
    rating_avg::float8 AS rating_avg, rating_count, booking_mode,
    min_lead_minutes, created_at, updated_at
FROM providers
WHERE id = $1
`

type GetProviderByIDRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Phone          *string
	Email          *string
	Description    *string
	City           *string
	Address        *string
	HasLocation    bool
	Lng            float64
	Lat            float64
	Timezone       string
	LogoUrl        *string
	LogoPublicID   *string
	CoverUrl       *string
	CoverPublicID  *string
	LicenseNumber  *string
	Status         string
	RatingAvg      float64
	RatingCount    int32
	BookingMode    string
	MinLeadMinutes int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetProviderByID(ctx context.Context, id uuid.UUID) (GetProviderByIDRow, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i GetProviderByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.City,
		&i.Address,
		&i.HasLocation,
		&i.Lng,
		&i.Lat,
		&i.Timezone,
		&i.LogoUrl,
		&i.LogoPublicID,
		&i.CoverUrl,
		&i.CoverPublicID,
		&i.LicenseNumber,
		&i.Status,
		&i.RatingAvg,
		&i.RatingCount,
		&i.BookingMode,
		&i.MinLeadMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProviderBySlug = `-- name: GetProviderBySlug :one
SELECT
    id, slug, name, phone, email, description, city, address,
    (location IS NOT NULL)::bool AS has_location,
    COALESCE(ST_X(location::geometry), 0)::float8 AS lng,
    COALESCE(ST_Y(location::geometry), 0)::float8 AS lat,
    timezone, logo_url, logo_public_id, cover_url, cover_public_id,
    license_number, status,
    rating_avg::float8 AS rating_avg, rating_count, booking_mode,
    min_lead_minutes, created_at, updated_at
FROM providers
WHERE slug = $1
`

type GetProviderBySlugRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Phone          *string
	Email          *string
	Description    *string
	City           *string
	Address        *string
	HasLocation    bool
	Lng            float64
	Lat            float64
	Timezone       string
	LogoUrl        *string
	LogoPublicID   *string
	CoverUrl       *string
	CoverPublicID  *string
	LicenseNumber  *string
	Status         string
	RatingAvg      float64
	RatingCount    int32
	BookingMode    string
	MinLeadMinutes int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetProviderBySlug(ctx context.Context, slug string) (GetProviderBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProviderBySlug, slug)
	var i GetProviderBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.City,
		&i.Address,
		&i.HasLocation,
		&i.Lng,
		&i.Lat,
		&i.Timezone,
		&i.LogoUrl,
		&i.LogoPublicID,
		&i.CoverUrl,
		&i.CoverPublicID,
		&i.LicenseNumber,
		&i.Status,
		&i.RatingAvg,
		&i.RatingCount,
		&i.BookingMode,
		&i.MinLeadMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProviders = `-- name: ListProviders :many
SELECT
    id, slug, name, phone, email, city, address,
    (location IS NOT NULL)::bool AS has_location,
    COALESCE(ST_X(location::geometry), 0)::float8 AS lng,
    COALESCE(ST_Y(location::geometry), 0)::float8 AS lat,
    timezone, logo_url, status,
    rating_avg::float8 AS rating_avg, rating_count, booking_mode,
    created_at, updated_at
FROM providers
WHERE ($1::text = '' OR status = $1)
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%' OR slug ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $4 OFFSET $3
`

type ListProvidersParams struct {
	Status       string
	Search       string
	ResultOffset int32
	ResultLimit  int32
}

type ListProvidersRow struct {
	ID          uuid.UUID
	Slug        string
	Name        string
	Phone       *string
	Email       *string
	City        *string
	Address     *string
	HasLocation bool
	Lng         float64
	Lat         float64
	Timezone    string
	LogoUrl     *string
	Status      string
	RatingAvg   float64
	RatingCount int32
	BookingMode string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListProviders(ctx context.Context, arg ListProvidersParams) ([]ListProvidersRow, error) {
	rows, err := q.db.Query(ctx, listProviders,
		arg.Status,
		arg.Search,
		arg.ResultOffset,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProvidersRow{}
	for rows.Next() {
		var i ListProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.City,
			&i.Address,
			&i.HasLocation,
			&i.Lng,
			&i.Lat,
			&i.Timezone,
			&i.LogoUrl,
			&i.Status,
			&i.RatingAvg,
			&i.RatingCount,
			&i.BookingMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProviderCover = `-- name: SetProviderCover :execrows
UPDATE providers
SET cover_url       = $1,
    cover_public_id = $2,
    updated_at      = now()
WHERE id = $3
`

type SetProviderCoverParams struct {
	CoverUrl      *string
	CoverPublicID *string
	ID            uuid.UUID
}

func (q *Queries) SetProviderCover(ctx context.Context, arg SetProviderCoverParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderCover, arg.CoverUrl, arg.CoverPublicID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProviderLogo = `-- name: SetProviderLogo :execrows

UPDATE providers
SET logo_url       = $1,
    logo_public_id = $2,
    updated_at     = now()
WHERE id = $3
`

type SetProviderLogoParams struct {
	LogoUrl      *string
	LogoPublicID *string
	ID           uuid.UUID
}

// Branding is written by its own statements rather than through UpdateProvider,
// which COALESCEs every column and therefore cannot express "remove this".
// Here a null pair is a deliberate clear, so one query covers set and remove.
func (q *Queries) SetProviderLogo(ctx context.Context, arg SetProviderLogoParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProviderLogo, arg.LogoUrl, arg.LogoPublicID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProviderStatus = `-- name: SetProviderStatus :one
UPDATE providers
SET status = $1, updated_at = now()
WHERE id = $2
RETURNING
    id, slug, name, status, booking_mode, timezone, min_lead_minutes,
    created_at, updated_at
`

type SetProviderStatusParams struct {
	Status string
	ID     uuid.UUID
}

type SetProviderStatusRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Status         string
	BookingMode    string
	Timezone       string
	MinLeadMinutes int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) SetProviderStatus(ctx context.Context, arg SetProviderStatusParams) (SetProviderStatusRow, error) {
	row := q.db.QueryRow(ctx, setProviderStatus, arg.Status, arg.ID)
	var i SetProviderStatusRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.BookingMode,
		&i.Timezone,
		&i.MinLeadMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const slugExists = `-- name: SlugExists :one
SELECT EXISTS (SELECT 1 FROM providers WHERE slug = $1)
`

func (q *Queries) SlugExists(ctx context.Context, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, slugExists, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateProvider = `-- name: UpdateProvider :one
UPDATE providers
SET name           = COALESCE($1, name),
    phone          = COALESCE($2, phone),
    email          = COALESCE($3, email),
    description    = COALESCE($4, description),
    city           = COALESCE($5, city),
    address        = COALESCE($6, address),
    timezone       = COALESCE($7, timezone),
    license_number = COALESCE($8, license_number),
    booking_mode   = COALESCE($9, booking_mode),
    min_lead_minutes = COALESCE($10, min_lead_minutes),
    -- location moves only when both halves of the coordinate are supplied
    location = CASE
        WHEN $11::float8 IS NULL OR $12::float8 IS NULL THEN location
        ELSE ST_SetSRID(ST_MakePoint($11::float8, $12::float8), 4326)::geography
    END,
    updated_at = now()
WHERE id = $13
RETURNING
    id, slug, name, phone, email, description, city, address,
    (location IS NOT NULL)::bool AS has_location,
    COALESCE(ST_X(location::geometry), 0)::float8 AS lng,
    COALESCE(ST_Y(location::geometry), 0)::float8 AS lat,
    timezone, logo_url, logo_public_id, cover_url, cover_public_id,
    license_number, status,
    rating_avg::float8 AS rating_avg, rating_count, booking_mode,
    min_lead_minutes, created_at, updated_at
`

type UpdateProviderParams struct {
	Name           *string
	Phone          *string
	Email          *string
	Description    *string
	City           *string
	Address        *string
	Timezone       *string
	LicenseNumber  *string
	BookingMode    *string
	MinLeadMinutes *int32
	Lng            *float64
	Lat            *float64
	ID             uuid.UUID
}

type UpdateProviderRow struct {
	ID             uuid.UUID
	Slug           string
	Name           string
	Phone          *string
	Email          *string
	Description    *string
	City           *string
	Address        *string
	HasLocation    bool
	Lng            float64
	Lat            float64
	Timezone       string
	LogoUrl        *string
	LogoPublicID   *string
	CoverUrl       *string
	CoverPublicID  *string
	LicenseNumber  *string
	Status         string
	RatingAvg      float64
	RatingCount    int32
	BookingMode    string
	MinLeadMinutes int32
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) UpdateProvider(ctx context.Context, arg UpdateProviderParams) (UpdateProviderRow, error) {
	row := q.db.QueryRow(ctx, updateProvider,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Description,
		arg.City,
		arg.Address,
		arg.Timezone,
		arg.LicenseNumber,
		arg.BookingMode,
		arg.MinLeadMinutes,
		arg.Lng,
		arg.Lat,
		arg.ID,
	)
	var i UpdateProviderRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Description,
		&i.City,
		&i.Address,
		&i.HasLocation,
		&i.Lng,
		&i.Lat,
		&i.Timezone,
		&i.LogoUrl,
		&i.LogoPublicID,
		&i.CoverUrl,
		&i.CoverPublicID,
		&i.LicenseNumber,
		&i.Status,
		&i.RatingAvg,
		&i.RatingCount,
		&i.BookingMode,
		&i.MinLeadMinutes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
