// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, id uuid.UUID) (AcceptInvitationRow, error)
	AddBookingOption(ctx context.Context, arg AddBookingOptionParams) error
	AddMember(ctx context.Context, arg AddMemberParams) (Member, error)
	// ---------------------------------------------------------------- provider_categories
	AddProviderCategory(ctx context.Context, arg AddProviderCategoryParams) error
	AddResourceService(ctx context.Context, arg AddResourceServiceParams) error
	BookingCodeExists(ctx context.Context, code string) (bool, error)
	// Guarded on consumed_at IS NULL so two simultaneous submissions of the same
	// code cannot both succeed; the loser sees zero rows and is treated as stale.
	ConsumeVerificationCode(ctx context.Context, id uuid.UUID) (int64, error)
	// Issuing a new code retires every earlier one for that address, so a resend
	// cannot leave two codes working at once.
	ConsumeVerificationCodesFor(ctx context.Context, arg ConsumeVerificationCodesForParams) error
	CountAllBookings(ctx context.Context, arg CountAllBookingsParams) (int64, error)
	CountBookingsByCustomer(ctx context.Context, arg CountBookingsByCustomerParams) (int64, error)
	CountBookingsByProvider(ctx context.Context, arg CountBookingsByProviderParams) (int64, error)
	// Guards against removing or demoting the last owner of a provider.
	CountOwners(ctx context.Context, providerID uuid.UUID) (int64, error)
	CountProviders(ctx context.Context, arg CountProvidersParams) (int64, error)
	CountServiceMedia(ctx context.Context, serviceID uuid.UUID) (int64, error)
	CountServicesPage(ctx context.Context, arg CountServicesPageParams) (int64, error)
	CountUsers(ctx context.Context, search string) (int64, error)
	// May fail with 23P01 (bookings_no_overlap). The store maps that to SLOT_TAKEN.
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	// ---------------------------------------------------------------- business hours
	CreateBusinessHours(ctx context.Context, arg CreateBusinessHoursParams) (CreateBusinessHoursRow, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCategoryAttribute(ctx context.Context, arg CreateCategoryAttributeParams) (CategoryAttribute, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error)
	CreateOptionGroup(ctx context.Context, arg CreateOptionGroupParams) (OptionGroup, error)
	// The `location` column is a PostGIS geography, which sqlc has no Go mapping
	// for. Every query therefore projects it as an explicit has_location/lng/lat
	// triple and never selects the raw column.
	CreateProvider(ctx context.Context, arg CreateProviderParams) (CreateProviderRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	// Times of day cross the sqlc boundary as minutes since midnight rather than
	// pgtype.Time: the slot algorithm is pure integer arithmetic that way, and
	// scheduling.TimeOfDay renders them back as "HH:MM" at the HTTP edge.
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	// ---------------------------------------------------------------- exceptions
	CreateScheduleException(ctx context.Context, arg CreateScheduleExceptionParams) (ScheduleException, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateServiceMedia(ctx context.Context, arg CreateServiceMediaParams) (ServiceMedium, error)
	// ---------------------------------------------------------------- options
	CreateServiceOption(ctx context.Context, arg CreateServiceOptionParams) (ServiceOption, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (CreateVerificationCodeRow, error)
	DeleteBusinessHours(ctx context.Context, arg DeleteBusinessHoursParams) (int64, error)
	DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteCategoryAttribute(ctx context.Context, id uuid.UUID) (int64, error)
	DeleteExpiredRefreshTokens(ctx context.Context) (int64, error)
	DeleteExpiredVerificationCodes(ctx context.Context) (int64, error)
	DeleteInvitation(ctx context.Context, arg DeleteInvitationParams) (int64, error)
	DeleteOptionGroup(ctx context.Context, arg DeleteOptionGroupParams) (int64, error)
	DeleteResource(ctx context.Context, arg DeleteResourceParams) (int64, error)
	DeleteScheduleException(ctx context.Context, arg DeleteScheduleExceptionParams) (int64, error)
	DeleteService(ctx context.Context, arg DeleteServiceParams) (int64, error)
	DeleteServiceMedia(ctx context.Context, arg DeleteServiceMediaParams) (string, error)
	DeleteServiceOption(ctx context.Context, arg DeleteServiceOptionParams) (int64, error)
	GetBooking(ctx context.Context, id uuid.UUID) (Booking, error)
	GetCategoryAttribute(ctx context.Context, id uuid.UUID) (CategoryAttribute, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetInvitationByTokenHash(ctx context.Context, tokenHash string) (Invitation, error)
	GetLiveVerificationCode(ctx context.Context, arg GetLiveVerificationCodeParams) (VerificationCode, error)
	// The membership check behind every /org/* request. `x-organization-id` is
	// client-supplied, so this runs before any org-scoped data is read.
	GetMembership(ctx context.Context, arg GetMembershipParams) (Member, error)
	GetOptionGroup(ctx context.Context, id uuid.UUID) (OptionGroup, error)
	GetProviderByID(ctx context.Context, id uuid.UUID) (GetProviderByIDRow, error)
	GetProviderBySlug(ctx context.Context, slug string) (GetProviderBySlugRow, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetResource(ctx context.Context, id uuid.UUID) (Resource, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	// Scoped on provider_id as well as id: a leaked media id from another tenant
	// still finds nothing.
	GetServiceMedia(ctx context.Context, arg GetServiceMediaParams) (ServiceMedium, error)
	// Everything booking needs about a service in one round trip: the provider's
	// booking_mode, timezone and status decide the rest of the flow.
	GetServiceWithProvider(ctx context.Context, id uuid.UUID) (GetServiceWithProviderRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	IncrementVerificationAttempts(ctx context.Context, id uuid.UUID) (int32, error)
	// Platform-admin cross-tenant listing. Deliberately separate from the
	// provider inbox query: it is not org-scoped, so it must never share a code
	// path with one that is.
	ListAllBookings(ctx context.Context, arg ListAllBookingsParams) ([]ListAllBookingsRow, error)
	ListBookingOptions(ctx context.Context, bookingIds []uuid.UUID) ([]BookingOption, error)
	ListBookingsByCustomer(ctx context.Context, arg ListBookingsByCustomerParams) ([]ListBookingsByCustomerRow, error)
	// The provider's inbox: a day at a time, optionally narrowed to one resource.
	ListBookingsByProvider(ctx context.Context, arg ListBookingsByProviderParams) ([]ListBookingsByProviderRow, error)
	ListBusinessHours(ctx context.Context, providerID uuid.UUID) ([]ListBusinessHoursRow, error)
	// Availability step 3: the day's window for one resource. Resource-specific
	// rows win; the provider-wide default (resource_id IS NULL) is the fallback.
	ListBusinessHoursForDay(ctx context.Context, arg ListBusinessHoursForDayParams) ([]ListBusinessHoursForDayRow, error)
	// Availability step 3: what already occupies these resources in this window.
	ListBusyIntervals(ctx context.Context, arg ListBusyIntervalsParams) ([]ListBusyIntervalsRow, error)
	ListCategories(ctx context.Context, activeOnly bool) ([]Category, error)
	// Drives the dynamic forms on both clients, and the validator on every write.
	ListCategoryAttributes(ctx context.Context, arg ListCategoryAttributesParams) ([]CategoryAttribute, error)
	// discovery/filter.go builds its jsonb containment filter from these, never
	// from raw query params.
	ListFilterableAttributes(ctx context.Context, categoryID uuid.UUID) ([]ListFilterableAttributesRow, error)
	ListInvitations(ctx context.Context, providerID uuid.UUID) ([]ListInvitationsRow, error)
	ListMembers(ctx context.Context, providerID uuid.UUID) ([]ListMembersRow, error)
	// Feeds the JWT `memberships` claim at sign-in and refresh.
	ListMembershipsByUser(ctx context.Context, userID uuid.UUID) ([]ListMembershipsByUserRow, error)
	ListOptionGroupsByService(ctx context.Context, serviceID uuid.UUID) ([]OptionGroup, error)
	ListOptionsByGroup(ctx context.Context, groupID uuid.UUID) ([]ServiceOption, error)
	// The pricing query: given the option ids a client claims it picked, return
	// what they actually are. Totals are recomputed from this, never trusted.
	ListOptionsByIDs(ctx context.Context, ids []uuid.UUID) ([]ListOptionsByIDsRow, error)
	// One round trip for a service's whole option tree.
	ListOptionsByService(ctx context.Context, serviceID uuid.UUID) ([]ServiceOption, error)
	ListProviderCategories(ctx context.Context, providerID uuid.UUID) ([]ListProviderCategoriesRow, error)
	ListProviders(ctx context.Context, arg ListProvidersParams) ([]ListProvidersRow, error)
	ListResourcesByProvider(ctx context.Context, arg ListResourcesByProviderParams) ([]Resource, error)
	// Availability step 2: which resources can actually perform this service.
	ListResourcesForService(ctx context.Context, serviceID uuid.UUID) ([]ListResourcesForServiceRow, error)
	ListScheduleExceptions(ctx context.Context, arg ListScheduleExceptionsParams) ([]ScheduleException, error)
	// Availability step 3: an exception for this date overrides business_hours.
	ListScheduleExceptionsForDate(ctx context.Context, arg ListScheduleExceptionsForDateParams) ([]ListScheduleExceptionsForDateRow, error)
	ListServiceIDsForResource(ctx context.Context, resourceID uuid.UUID) ([]uuid.UUID, error)
	ListServiceMedia(ctx context.Context, serviceID uuid.UUID) ([]ServiceMedium, error)
	ListServicesByProvider(ctx context.Context, arg ListServicesByProviderParams) ([]Service, error)
	// The org catalog list: search, filter, sort and paginate, all in the
	// database. sqlc cannot interpolate an ORDER BY, so the sort key arrives as a
	// whitelisted string and is resolved by CASE — which keeps it a bound
	// parameter rather than concatenated SQL.
	//
	// The join is what lets `category` be a sortable column: sorting on
	// category_id would order by a uuid, which is nothing a reader recognises.
	ListServicesPage(ctx context.Context, arg ListServicesPageParams) ([]ListServicesPageRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	MarkEmailVerified(ctx context.Context, id uuid.UUID) error
	// New images land after the ones already there, so upload order is preserved
	// without the client having to say so.
	NextServiceMediaSortOrder(ctx context.Context, serviceID uuid.UUID) (int32, error)
	ProviderBookingStats(ctx context.Context, arg ProviderBookingStatsParams) (ProviderBookingStatsRow, error)
	RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error)
	RemoveProviderCategory(ctx context.Context, arg RemoveProviderCategoryParams) (int64, error)
	RemoveResourceService(ctx context.Context, arg RemoveResourceServiceParams) (int64, error)
	ReplaceProviderCategories(ctx context.Context, arg ReplaceProviderCategoriesParams) error
	// Used on sign-out-everywhere and on refresh-token reuse detection.
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	// Returns the number of rows it changed, which is how rotation stays safe
	// under concurrency: two simultaneous refreshes with the same token both pass
	// the read, but only one of them can move revoked_at from NULL.
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) (int64, error)
	RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) (RevokeRefreshTokenByHashRow, error)
	// Catalog-wide figures for the provider dashboard's stat cards. Deliberately
	// unfiltered: these describe the whole catalog, while the table beneath them
	// describes the current query.
	ServiceCatalogStats(ctx context.Context, providerID uuid.UUID) (ServiceCatalogStatsRow, error)
	ServiceCountByCategory(ctx context.Context, providerID uuid.UUID) ([]ServiceCountByCategoryRow, error)
	ServiceExistsForProvider(ctx context.Context, arg ServiceExistsForProviderParams) (bool, error)
	// Services added per month over a rolling window, for the catalog-growth area
	// chart. `prior_total` is what existed before the window, so the running total
	// the client draws starts from the truth rather than from zero.
	ServicesAddedByMonth(ctx context.Context, arg ServicesAddedByMonthParams) ([]ServicesAddedByMonthRow, error)
	ServicesCreatedBefore(ctx context.Context, arg ServicesCreatedBeforeParams) (int64, error)
	SetProviderStatus(ctx context.Context, arg SetProviderStatusParams) (SetProviderStatusRow, error)
	SetServiceImage(ctx context.Context, arg SetServiceImageParams) (SetServiceImageRow, error)
	SetUserFCMToken(ctx context.Context, arg SetUserFCMTokenParams) error
	SlugExists(ctx context.Context, slug string) (bool, error)
	// The state machine writes through here. The `from_status` guard makes the
	// transition atomic: a concurrent update leaves this returning no rows.
	TransitionBooking(ctx context.Context, arg TransitionBookingParams) (Booking, error)
	UpdateBusinessHours(ctx context.Context, arg UpdateBusinessHoursParams) (UpdateBusinessHoursRow, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCategoryAttribute(ctx context.Context, arg UpdateCategoryAttributeParams) (CategoryAttribute, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (Member, error)
	UpdateOptionGroup(ctx context.Context, arg UpdateOptionGroupParams) (OptionGroup, error)
	UpdateProvider(ctx context.Context, arg UpdateProviderParams) (UpdateProviderRow, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
	UpdateScheduleException(ctx context.Context, arg UpdateScheduleExceptionParams) (ScheduleException, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateServiceMedia(ctx context.Context, arg UpdateServiceMediaParams) (ServiceMedium, error)
	UpdateServiceOption(ctx context.Context, arg UpdateServiceOptionParams) (ServiceOption, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error)
}

var _ Querier = (*Queries)(nil)
