// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scheduling.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addResourceService = `-- name: AddResourceService :exec
INSERT INTO resource_services (resource_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddResourceServiceParams struct {
	ResourceID uuid.UUID
	ServiceID  uuid.UUID
}

func (q *Queries) AddResourceService(ctx context.Context, arg AddResourceServiceParams) error {
	_, err := q.db.Exec(ctx, addResourceService, arg.ResourceID, arg.ServiceID)
	return err
}

const createBusinessHours = `-- name: CreateBusinessHours :one

INSERT INTO business_hours (provider_id, resource_id, weekday, opens_at, closes_at)
VALUES (
    $1, $2, $3,
    make_interval(mins => $4::int)::time,
    make_interval(mins => $5::int)::time
)
RETURNING id, provider_id, resource_id, weekday,
          (EXTRACT(EPOCH FROM opens_at) / 60)::int AS opens_minute,
          (EXTRACT(EPOCH FROM closes_at) / 60)::int AS closes_minute,
          created_at, updated_at
`

type CreateBusinessHoursParams struct {
	ProviderID   uuid.UUID
	ResourceID   *uuid.UUID
	Weekday      int32
	OpensMinute  int32
	ClosesMinute int32
}

type CreateBusinessHoursRow struct {
	ID           uuid.UUID
	ProviderID   uuid.UUID
	ResourceID   *uuid.UUID
	Weekday      int32
	OpensMinute  int32
	ClosesMinute int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

// ---------------------------------------------------------------- business hours
func (q *Queries) CreateBusinessHours(ctx context.Context, arg CreateBusinessHoursParams) (CreateBusinessHoursRow, error) {
	row := q.db.QueryRow(ctx, createBusinessHours,
		arg.ProviderID,
		arg.ResourceID,
		arg.Weekday,
		arg.OpensMinute,
		arg.ClosesMinute,
	)
	var i CreateBusinessHoursRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ResourceID,
		&i.Weekday,
		&i.OpensMinute,
		&i.ClosesMinute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createResource = `-- name: CreateResource :one

INSERT INTO resources (provider_id, name, user_id, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_id, name, user_id, is_active, created_at, updated_at
`

type CreateResourceParams struct {
	ProviderID uuid.UUID
	Name       string
	UserID     *uuid.UUID
	IsActive   bool
}

// Times of day cross the sqlc boundary as minutes since midnight rather than
// pgtype.Time: the slot algorithm is pure integer arithmetic that way, and
// scheduling.TimeOfDay renders them back as "HH:MM" at the HTTP edge.
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource,
		arg.ProviderID,
		arg.Name,
		arg.UserID,
		arg.IsActive,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createScheduleException = `-- name: CreateScheduleException :one

INSERT INTO schedule_exceptions (provider_id, resource_id, date, is_closed, opens_at, closes_at, reason)
VALUES (
    $1, $2, $3, $4,
    make_interval(mins => $5::int)::time,
    make_interval(mins => $6::int)::time,
    $7
)
RETURNING id, provider_id, resource_id, date, is_closed,
          opens_at, closes_at,
          reason, created_at, updated_at
`

type CreateScheduleExceptionParams struct {
	ProviderID   uuid.UUID
	ResourceID   *uuid.UUID
	Date         time.Time
	IsClosed     bool
	OpensMinute  *int32
	ClosesMinute *int32
	Reason       *string
}

// ---------------------------------------------------------------- exceptions
func (q *Queries) CreateScheduleException(ctx context.Context, arg CreateScheduleExceptionParams) (ScheduleException, error) {
	row := q.db.QueryRow(ctx, createScheduleException,
		arg.ProviderID,
		arg.ResourceID,
		arg.Date,
		arg.IsClosed,
		arg.OpensMinute,
		arg.ClosesMinute,
		arg.Reason,
	)
	var i ScheduleException
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ResourceID,
		&i.Date,
		&i.IsClosed,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBusinessHours = `-- name: DeleteBusinessHours :execrows
DELETE FROM business_hours WHERE id = $1 AND provider_id = $2
`

type DeleteBusinessHoursParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) DeleteBusinessHours(ctx context.Context, arg DeleteBusinessHoursParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBusinessHours, arg.ID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBusinessHoursForScope = `-- name: DeleteBusinessHoursForScope :execrows
DELETE FROM business_hours
WHERE provider_id = $1
  AND resource_id IS NOT DISTINCT FROM $2
`

type DeleteBusinessHoursForScopeParams struct {
	ProviderID uuid.UUID
	ResourceID *uuid.UUID
}

// Clears one scope so the whole week can be rewritten in a transaction, which
// is what an hours editor actually does: it saves a week, not a row. A null
// resource_id is its own scope, so replacing the provider-wide default leaves
// per-resource overrides alone.
func (q *Queries) DeleteBusinessHoursForScope(ctx context.Context, arg DeleteBusinessHoursForScopeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBusinessHoursForScope, arg.ProviderID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteResource = `-- name: DeleteResource :execrows
DELETE FROM resources WHERE id = $1 AND provider_id = $2
`

type DeleteResourceParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) DeleteResource(ctx context.Context, arg DeleteResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteResource, arg.ID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteScheduleException = `-- name: DeleteScheduleException :execrows
DELETE FROM schedule_exceptions WHERE id = $1 AND provider_id = $2
`

type DeleteScheduleExceptionParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) DeleteScheduleException(ctx context.Context, arg DeleteScheduleExceptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteScheduleException, arg.ID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getResource = `-- name: GetResource :one
SELECT id, provider_id, name, user_id, is_active, created_at, updated_at
FROM resources
WHERE id = $1
`

func (q *Queries) GetResource(ctx context.Context, id uuid.UUID) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, id)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBusinessHours = `-- name: ListBusinessHours :many
SELECT id, provider_id, resource_id, weekday,
       (EXTRACT(EPOCH FROM opens_at) / 60)::int AS opens_minute,
       (EXTRACT(EPOCH FROM closes_at) / 60)::int AS closes_minute,
       created_at, updated_at
FROM business_hours
WHERE provider_id = $1
ORDER BY weekday, opens_at
`

type ListBusinessHoursRow struct {
	ID           uuid.UUID
	ProviderID   uuid.UUID
	ResourceID   *uuid.UUID
	Weekday      int32
	OpensMinute  int32
	ClosesMinute int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) ListBusinessHours(ctx context.Context, providerID uuid.UUID) ([]ListBusinessHoursRow, error) {
	rows, err := q.db.Query(ctx, listBusinessHours, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessHoursRow{}
	for rows.Next() {
		var i ListBusinessHoursRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ResourceID,
			&i.Weekday,
			&i.OpensMinute,
			&i.ClosesMinute,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBusinessHoursForDay = `-- name: ListBusinessHoursForDay :many
SELECT id, provider_id, resource_id, weekday,
       (EXTRACT(EPOCH FROM opens_at) / 60)::int AS opens_minute,
       (EXTRACT(EPOCH FROM closes_at) / 60)::int AS closes_minute
FROM business_hours
WHERE provider_id = $1
  AND weekday = $2
  AND (resource_id IS NULL OR resource_id = ANY ($3::uuid[]))
ORDER BY opens_at
`

type ListBusinessHoursForDayParams struct {
	ProviderID  uuid.UUID
	Weekday     int32
	ResourceIds []uuid.UUID
}

type ListBusinessHoursForDayRow struct {
	ID           uuid.UUID
	ProviderID   uuid.UUID
	ResourceID   *uuid.UUID
	Weekday      int32
	OpensMinute  int32
	ClosesMinute int32
}

// Availability step 3: the day's window for one resource. Resource-specific
// rows win; the provider-wide default (resource_id IS NULL) is the fallback.
func (q *Queries) ListBusinessHoursForDay(ctx context.Context, arg ListBusinessHoursForDayParams) ([]ListBusinessHoursForDayRow, error) {
	rows, err := q.db.Query(ctx, listBusinessHoursForDay, arg.ProviderID, arg.Weekday, arg.ResourceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBusinessHoursForDayRow{}
	for rows.Next() {
		var i ListBusinessHoursForDayRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ResourceID,
			&i.Weekday,
			&i.OpensMinute,
			&i.ClosesMinute,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesByProvider = `-- name: ListResourcesByProvider :many
SELECT id, provider_id, name, user_id, is_active, created_at, updated_at
FROM resources
WHERE provider_id = $1
  AND ($2::bool = false OR is_active)
ORDER BY name
`

type ListResourcesByProviderParams struct {
	ProviderID uuid.UUID
	ActiveOnly bool
}

func (q *Queries) ListResourcesByProvider(ctx context.Context, arg ListResourcesByProviderParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResourcesByProvider, arg.ProviderID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.UserID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResourcesForService = `-- name: ListResourcesForService :many
SELECT r.id, r.provider_id, r.name, r.user_id, r.is_active
FROM resource_services rs
JOIN resources r ON r.id = rs.resource_id
WHERE rs.service_id = $1 AND r.is_active
ORDER BY r.name
`

type ListResourcesForServiceRow struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
	Name       string
	UserID     *uuid.UUID
	IsActive   bool
}

// Availability step 2: which resources can actually perform this service.
func (q *Queries) ListResourcesForService(ctx context.Context, serviceID uuid.UUID) ([]ListResourcesForServiceRow, error) {
	rows, err := q.db.Query(ctx, listResourcesForService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListResourcesForServiceRow{}
	for rows.Next() {
		var i ListResourcesForServiceRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Name,
			&i.UserID,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleExceptions = `-- name: ListScheduleExceptions :many
SELECT id, provider_id, resource_id, date, is_closed,
       opens_at, closes_at,
       reason, created_at, updated_at
FROM schedule_exceptions
WHERE provider_id = $1
  AND ($2::date IS NULL OR date >= $2)
  AND ($3::date IS NULL OR date <= $3)
ORDER BY date
`

type ListScheduleExceptionsParams struct {
	ProviderID uuid.UUID
	FromDate   *time.Time
	ToDate     *time.Time
}

func (q *Queries) ListScheduleExceptions(ctx context.Context, arg ListScheduleExceptionsParams) ([]ScheduleException, error) {
	rows, err := q.db.Query(ctx, listScheduleExceptions, arg.ProviderID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScheduleException{}
	for rows.Next() {
		var i ScheduleException
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ResourceID,
			&i.Date,
			&i.IsClosed,
			&i.OpensAt,
			&i.ClosesAt,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduleExceptionsForDate = `-- name: ListScheduleExceptionsForDate :many
SELECT id, provider_id, resource_id, date, is_closed,
       opens_at, closes_at,
       reason
FROM schedule_exceptions
WHERE provider_id = $1 AND date = $2
`

type ListScheduleExceptionsForDateParams struct {
	ProviderID uuid.UUID
	Date       time.Time
}

type ListScheduleExceptionsForDateRow struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
	ResourceID *uuid.UUID
	Date       time.Time
	IsClosed   bool
	OpensAt    pgtype.Time
	ClosesAt   pgtype.Time
	Reason     *string
}

// Availability step 3: an exception for this date overrides business_hours.
func (q *Queries) ListScheduleExceptionsForDate(ctx context.Context, arg ListScheduleExceptionsForDateParams) ([]ListScheduleExceptionsForDateRow, error) {
	rows, err := q.db.Query(ctx, listScheduleExceptionsForDate, arg.ProviderID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListScheduleExceptionsForDateRow{}
	for rows.Next() {
		var i ListScheduleExceptionsForDateRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.ResourceID,
			&i.Date,
			&i.IsClosed,
			&i.OpensAt,
			&i.ClosesAt,
			&i.Reason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceIDsForResource = `-- name: ListServiceIDsForResource :many
SELECT service_id FROM resource_services WHERE resource_id = $1
`

func (q *Queries) ListServiceIDsForResource(ctx context.Context, resourceID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listServiceIDsForResource, resourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var service_id uuid.UUID
		if err := rows.Scan(&service_id); err != nil {
			return nil, err
		}
		items = append(items, service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeResourceService = `-- name: RemoveResourceService :execrows
DELETE FROM resource_services
WHERE resource_id = $1 AND service_id = $2
`

type RemoveResourceServiceParams struct {
	ResourceID uuid.UUID
	ServiceID  uuid.UUID
}

func (q *Queries) RemoveResourceService(ctx context.Context, arg RemoveResourceServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeResourceService, arg.ResourceID, arg.ServiceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBusinessHours = `-- name: UpdateBusinessHours :one
UPDATE business_hours
SET weekday   = COALESCE($1, weekday),
    opens_at  = COALESCE(make_interval(mins => $2::int)::time, opens_at),
    closes_at = COALESCE(make_interval(mins => $3::int)::time, closes_at),
    updated_at = now()
WHERE id = $4 AND provider_id = $5
RETURNING id, provider_id, resource_id, weekday,
          (EXTRACT(EPOCH FROM opens_at) / 60)::int AS opens_minute,
          (EXTRACT(EPOCH FROM closes_at) / 60)::int AS closes_minute,
          created_at, updated_at
`

type UpdateBusinessHoursParams struct {
	Weekday      *int32
	OpensMinute  *int32
	ClosesMinute *int32
	ID           uuid.UUID
	ProviderID   uuid.UUID
}

type UpdateBusinessHoursRow struct {
	ID           uuid.UUID
	ProviderID   uuid.UUID
	ResourceID   *uuid.UUID
	Weekday      int32
	OpensMinute  int32
	ClosesMinute int32
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) UpdateBusinessHours(ctx context.Context, arg UpdateBusinessHoursParams) (UpdateBusinessHoursRow, error) {
	row := q.db.QueryRow(ctx, updateBusinessHours,
		arg.Weekday,
		arg.OpensMinute,
		arg.ClosesMinute,
		arg.ID,
		arg.ProviderID,
	)
	var i UpdateBusinessHoursRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ResourceID,
		&i.Weekday,
		&i.OpensMinute,
		&i.ClosesMinute,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET name       = COALESCE($1, name),
    -- COALESCE alone can never write a NULL back, so "this chair is nobody's
    -- again" would be unsayable: reassigning works, unassigning does not.
    -- @unassign_user is that missing half.
    user_id    = CASE
                     WHEN $2::bool THEN NULL
                     ELSE COALESCE($3, user_id)
                 END,
    is_active  = COALESCE($4, is_active),
    updated_at = now()
WHERE id = $5 AND provider_id = $6
RETURNING id, provider_id, name, user_id, is_active, created_at, updated_at
`

type UpdateResourceParams struct {
	Name         *string
	UnassignUser bool
	UserID       *uuid.UUID
	IsActive     *bool
	ID           uuid.UUID
	ProviderID   uuid.UUID
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.Name,
		arg.UnassignUser,
		arg.UserID,
		arg.IsActive,
		arg.ID,
		arg.ProviderID,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Name,
		&i.UserID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateScheduleException = `-- name: UpdateScheduleException :one
UPDATE schedule_exceptions
SET date       = COALESCE($1, date),
    is_closed  = COALESCE($2, is_closed),
    opens_at   = make_interval(mins => $3::int)::time,
    closes_at  = make_interval(mins => $4::int)::time,
    reason     = COALESCE($5, reason),
    updated_at = now()
WHERE id = $6 AND provider_id = $7
RETURNING id, provider_id, resource_id, date, is_closed,
          opens_at, closes_at,
          reason, created_at, updated_at
`

type UpdateScheduleExceptionParams struct {
	Date         *time.Time
	IsClosed     *bool
	OpensMinute  *int32
	ClosesMinute *int32
	Reason       *string
	ID           uuid.UUID
	ProviderID   uuid.UUID
}

func (q *Queries) UpdateScheduleException(ctx context.Context, arg UpdateScheduleExceptionParams) (ScheduleException, error) {
	row := q.db.QueryRow(ctx, updateScheduleException,
		arg.Date,
		arg.IsClosed,
		arg.OpensMinute,
		arg.ClosesMinute,
		arg.Reason,
		arg.ID,
		arg.ProviderID,
	)
	var i ScheduleException
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.ResourceID,
		&i.Date,
		&i.IsClosed,
		&i.OpensAt,
		&i.ClosesAt,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
