// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: service_media.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countServiceMedia = `-- name: CountServiceMedia :one
SELECT count(*) FROM service_media WHERE service_id = $1
`

func (q *Queries) CountServiceMedia(ctx context.Context, serviceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countServiceMedia, serviceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createServiceMedia = `-- name: CreateServiceMedia :one
INSERT INTO service_media (service_id, provider_id, image_url, image_public_id, caption, sort_order)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, service_id, provider_id, image_url, image_public_id, caption, sort_order, created_at
`

type CreateServiceMediaParams struct {
	ServiceID     uuid.UUID
	ProviderID    uuid.UUID
	ImageUrl      string
	ImagePublicID string
	Caption       *string
	SortOrder     int32
}

func (q *Queries) CreateServiceMedia(ctx context.Context, arg CreateServiceMediaParams) (ServiceMedium, error) {
	row := q.db.QueryRow(ctx, createServiceMedia,
		arg.ServiceID,
		arg.ProviderID,
		arg.ImageUrl,
		arg.ImagePublicID,
		arg.Caption,
		arg.SortOrder,
	)
	var i ServiceMedium
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.ProviderID,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServiceMedia = `-- name: DeleteServiceMedia :one
DELETE FROM service_media
WHERE id = $1 AND provider_id = $2
RETURNING image_public_id
`

type DeleteServiceMediaParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) DeleteServiceMedia(ctx context.Context, arg DeleteServiceMediaParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteServiceMedia, arg.ID, arg.ProviderID)
	var image_public_id string
	err := row.Scan(&image_public_id)
	return image_public_id, err
}

const getServiceMedia = `-- name: GetServiceMedia :one
SELECT id, service_id, provider_id, image_url, image_public_id, caption,
       sort_order, created_at
FROM service_media
WHERE id = $1 AND provider_id = $2
`

type GetServiceMediaParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

// Scoped on provider_id as well as id: a leaked media id from another tenant
// still finds nothing.
func (q *Queries) GetServiceMedia(ctx context.Context, arg GetServiceMediaParams) (ServiceMedium, error) {
	row := q.db.QueryRow(ctx, getServiceMedia, arg.ID, arg.ProviderID)
	var i ServiceMedium
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.ProviderID,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listServiceMedia = `-- name: ListServiceMedia :many
SELECT id, service_id, provider_id, image_url, image_public_id, caption,
       sort_order, created_at
FROM service_media
WHERE service_id = $1
ORDER BY sort_order, created_at
`

func (q *Queries) ListServiceMedia(ctx context.Context, serviceID uuid.UUID) ([]ServiceMedium, error) {
	rows, err := q.db.Query(ctx, listServiceMedia, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServiceMedium{}
	for rows.Next() {
		var i ServiceMedium
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.ProviderID,
			&i.ImageUrl,
			&i.ImagePublicID,
			&i.Caption,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextServiceMediaSortOrder = `-- name: NextServiceMediaSortOrder :one
SELECT COALESCE(max(sort_order) + 1, 0)::int
FROM service_media
WHERE service_id = $1
`

// New images land after the ones already there, so upload order is preserved
// without the client having to say so.
func (q *Queries) NextServiceMediaSortOrder(ctx context.Context, serviceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextServiceMediaSortOrder, serviceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const serviceExistsForProvider = `-- name: ServiceExistsForProvider :one
SELECT EXISTS (
    SELECT 1 FROM services WHERE id = $1 AND provider_id = $2
)
`

type ServiceExistsForProviderParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) ServiceExistsForProvider(ctx context.Context, arg ServiceExistsForProviderParams) (bool, error) {
	row := q.db.QueryRow(ctx, serviceExistsForProvider, arg.ID, arg.ProviderID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateServiceMedia = `-- name: UpdateServiceMedia :one
UPDATE service_media
SET caption    = COALESCE($1, caption),
    sort_order = COALESCE($2, sort_order)
WHERE id = $3 AND provider_id = $4
RETURNING id, service_id, provider_id, image_url, image_public_id, caption, sort_order, created_at
`

type UpdateServiceMediaParams struct {
	Caption    *string
	SortOrder  *int32
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) UpdateServiceMedia(ctx context.Context, arg UpdateServiceMediaParams) (ServiceMedium, error) {
	row := q.db.QueryRow(ctx, updateServiceMedia,
		arg.Caption,
		arg.SortOrder,
		arg.ID,
		arg.ProviderID,
	)
	var i ServiceMedium
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.ProviderID,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.Caption,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
