// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createService = `-- name: CreateService :one
INSERT INTO services (
    provider_id, category_id, name, description, price_cents, currency,
    duration_minutes, buffer_minutes, attributes, is_active
)
VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10
)
RETURNING id, provider_id, category_id, name, description, price_cents, currency,
          duration_minutes, buffer_minutes, attributes, image_url, image_public_id,
          is_active, created_at, updated_at
`

type CreateServiceParams struct {
	ProviderID      uuid.UUID
	CategoryID      uuid.UUID
	Name            string
	Description     *string
	PriceCents      int32
	Currency        string
	DurationMinutes int32
	BufferMinutes   int32
	Attributes      []byte
	IsActive        bool
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.ProviderID,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.Attributes,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.Attributes,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :execrows
DELETE FROM services WHERE id = $1 AND provider_id = $2
`

type DeleteServiceParams struct {
	ID         uuid.UUID
	ProviderID uuid.UUID
}

func (q *Queries) DeleteService(ctx context.Context, arg DeleteServiceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteService, arg.ID, arg.ProviderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getService = `-- name: GetService :one
SELECT id, provider_id, category_id, name, description, price_cents, currency,
       duration_minutes, buffer_minutes, attributes, image_url, image_public_id,
       is_active, created_at, updated_at
FROM services
WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.Attributes,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceWithProvider = `-- name: GetServiceWithProvider :one
SELECT s.id, s.provider_id, s.category_id, s.name, s.description, s.price_cents,
       s.currency, s.duration_minutes, s.buffer_minutes, s.attributes,
       s.image_url, s.is_active,
       p.slug AS provider_slug, p.name AS provider_name, p.status AS provider_status,
       p.booking_mode, p.timezone, p.min_lead_minutes
FROM services s
JOIN providers p ON p.id = s.provider_id
WHERE s.id = $1
`

type GetServiceWithProviderRow struct {
	ID              uuid.UUID
	ProviderID      uuid.UUID
	CategoryID      uuid.UUID
	Name            string
	Description     *string
	PriceCents      int32
	Currency        string
	DurationMinutes int32
	BufferMinutes   int32
	Attributes      []byte
	ImageUrl        *string
	IsActive        bool
	ProviderSlug    string
	ProviderName    string
	ProviderStatus  string
	BookingMode     string
	Timezone        string
	MinLeadMinutes  int32
}

// Everything booking needs about a service in one round trip: the provider's
// booking_mode, timezone and status decide the rest of the flow.
func (q *Queries) GetServiceWithProvider(ctx context.Context, id uuid.UUID) (GetServiceWithProviderRow, error) {
	row := q.db.QueryRow(ctx, getServiceWithProvider, id)
	var i GetServiceWithProviderRow
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.Attributes,
		&i.ImageUrl,
		&i.IsActive,
		&i.ProviderSlug,
		&i.ProviderName,
		&i.ProviderStatus,
		&i.BookingMode,
		&i.Timezone,
		&i.MinLeadMinutes,
	)
	return i, err
}

const listServicesByProvider = `-- name: ListServicesByProvider :many
SELECT id, provider_id, category_id, name, description, price_cents, currency,
       duration_minutes, buffer_minutes, attributes, image_url, image_public_id,
       is_active, created_at, updated_at
FROM services
WHERE provider_id = $1
  AND ($2::bool = false OR is_active)
ORDER BY name
`

type ListServicesByProviderParams struct {
	ProviderID uuid.UUID
	ActiveOnly bool
}

func (q *Queries) ListServicesByProvider(ctx context.Context, arg ListServicesByProviderParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesByProvider, arg.ProviderID, arg.ActiveOnly)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.DurationMinutes,
			&i.BufferMinutes,
			&i.Attributes,
			&i.ImageUrl,
			&i.ImagePublicID,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServiceImage = `-- name: SetServiceImage :one
UPDATE services
SET image_url = $1, image_public_id = $2,
    updated_at = now()
WHERE id = $3 AND provider_id = $4
RETURNING id, image_url, image_public_id
`

type SetServiceImageParams struct {
	ImageUrl      *string
	ImagePublicID *string
	ID            uuid.UUID
	ProviderID    uuid.UUID
}

type SetServiceImageRow struct {
	ID            uuid.UUID
	ImageUrl      *string
	ImagePublicID *string
}

func (q *Queries) SetServiceImage(ctx context.Context, arg SetServiceImageParams) (SetServiceImageRow, error) {
	row := q.db.QueryRow(ctx, setServiceImage,
		arg.ImageUrl,
		arg.ImagePublicID,
		arg.ID,
		arg.ProviderID,
	)
	var i SetServiceImageRow
	err := row.Scan(&i.ID, &i.ImageUrl, &i.ImagePublicID)
	return i, err
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET category_id      = COALESCE($1, category_id),
    name             = COALESCE($2, name),
    description      = COALESCE($3, description),
    price_cents      = COALESCE($4, price_cents),
    currency         = COALESCE($5, currency),
    duration_minutes = COALESCE($6, duration_minutes),
    buffer_minutes   = COALESCE($7, buffer_minutes),
    attributes       = COALESCE($8, attributes),
    is_active        = COALESCE($9, is_active),
    updated_at       = now()
WHERE id = $10 AND provider_id = $11
RETURNING id, provider_id, category_id, name, description, price_cents, currency,
          duration_minutes, buffer_minutes, attributes, image_url, image_public_id,
          is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	CategoryID      *uuid.UUID
	Name            *string
	Description     *string
	PriceCents      *int32
	Currency        *string
	DurationMinutes *int32
	BufferMinutes   *int32
	Attributes      []byte
	IsActive        *bool
	ID              uuid.UUID
	ProviderID      uuid.UUID
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.Attributes,
		arg.IsActive,
		arg.ID,
		arg.ProviderID,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.Attributes,
		&i.ImageUrl,
		&i.ImagePublicID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
