// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%')
`

func (q *Queries) CountUsers(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, phone, password_hash, platform_role)
VALUES ($1, lower($2), $3, $4, $5)
RETURNING id, name, email, phone, platform_role, email_verified, fcm_token, created_at, updated_at
`

type CreateUserParams struct {
	Name         string
	Email        string
	Phone        *string
	PasswordHash string
	PlatformRole string
}

type CreateUserRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	Phone         *string
	PlatformRole  string
	EmailVerified bool
	FcmToken      *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.PlatformRole,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PlatformRole,
		&i.EmailVerified,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, password_hash, platform_role, email_verified,
       fcm_token, created_at, updated_at
FROM users
WHERE email = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.PlatformRole,
		&i.EmailVerified,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, platform_role, email_verified, fcm_token,
       created_at, updated_at
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	Phone         *string
	PlatformRole  string
	EmailVerified bool
	FcmToken      *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PlatformRole,
		&i.EmailVerified,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, phone, platform_role, email_verified, created_at, updated_at
FROM users
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%' OR email ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $2
`

type ListUsersParams struct {
	Search       string
	ResultOffset int32
	ResultLimit  int32
}

type ListUsersRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	Phone         *string
	PlatformRole  string
	EmailVerified bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Search, arg.ResultOffset, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.PlatformRole,
			&i.EmailVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserFCMToken = `-- name: SetUserFCMToken :exec
UPDATE users
SET fcm_token = $1, updated_at = now()
WHERE id = $2
`

type SetUserFCMTokenParams struct {
	FcmToken *string
	ID       uuid.UUID
}

func (q *Queries) SetUserFCMToken(ctx context.Context, arg SetUserFCMTokenParams) error {
	_, err := q.db.Exec(ctx, setUserFCMToken, arg.FcmToken, arg.ID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name  = COALESCE($1, name),
    phone = COALESCE($2, phone),
    updated_at = now()
WHERE id = $3
RETURNING id, name, email, phone, platform_role, email_verified, fcm_token,
          created_at, updated_at
`

type UpdateUserProfileParams struct {
	Name  *string
	Phone *string
	ID    uuid.UUID
}

type UpdateUserProfileRow struct {
	ID            uuid.UUID
	Name          string
	Email         string
	Phone         *string
	PlatformRole  string
	EmailVerified bool
	FcmToken      *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UpdateUserProfileRow, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.Name, arg.Phone, arg.ID)
	var i UpdateUserProfileRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.PlatformRole,
		&i.EmailVerified,
		&i.FcmToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
