// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification_codes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeVerificationCode = `-- name: ConsumeVerificationCode :execrows
UPDATE verification_codes
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

// Guarded on consumed_at IS NULL so two simultaneous submissions of the same
// code cannot both succeed; the loser sees zero rows and is treated as stale.
func (q *Queries) ConsumeVerificationCode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeVerificationCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeVerificationCodesFor = `-- name: ConsumeVerificationCodesFor :exec
UPDATE verification_codes
SET consumed_at = now()
WHERE channel = $1 AND destination = lower($2) AND consumed_at IS NULL
`

type ConsumeVerificationCodesForParams struct {
	Channel     string
	Destination string
}

// Issuing a new code retires every earlier one for that address, so a resend
// cannot leave two codes working at once.
func (q *Queries) ConsumeVerificationCodesFor(ctx context.Context, arg ConsumeVerificationCodesForParams) error {
	_, err := q.db.Exec(ctx, consumeVerificationCodesFor, arg.Channel, arg.Destination)
	return err
}

const createVerificationCode = `-- name: CreateVerificationCode :one
INSERT INTO verification_codes (user_id, channel, destination, code_hash, expires_at)
VALUES ($1, $2, lower($3), $4, $5)
RETURNING id, user_id, channel, destination, attempts, expires_at, consumed_at, created_at
`

type CreateVerificationCodeParams struct {
	UserID      uuid.UUID
	Channel     string
	Destination string
	CodeHash    string
	ExpiresAt   time.Time
}

type CreateVerificationCodeRow struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Channel     string
	Destination string
	Attempts    int32
	ExpiresAt   time.Time
	ConsumedAt  *time.Time
	CreatedAt   time.Time
}

func (q *Queries) CreateVerificationCode(ctx context.Context, arg CreateVerificationCodeParams) (CreateVerificationCodeRow, error) {
	row := q.db.QueryRow(ctx, createVerificationCode,
		arg.UserID,
		arg.Channel,
		arg.Destination,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	var i CreateVerificationCodeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Destination,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredVerificationCodes = `-- name: DeleteExpiredVerificationCodes :execrows
DELETE FROM verification_codes
WHERE expires_at < now() - interval '7 days'
`

func (q *Queries) DeleteExpiredVerificationCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredVerificationCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLiveVerificationCode = `-- name: GetLiveVerificationCode :one
SELECT id, user_id, channel, destination, code_hash, attempts, expires_at,
       consumed_at, created_at
FROM verification_codes
WHERE channel = $1 AND destination = lower($2) AND consumed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

type GetLiveVerificationCodeParams struct {
	Channel     string
	Destination string
}

func (q *Queries) GetLiveVerificationCode(ctx context.Context, arg GetLiveVerificationCodeParams) (VerificationCode, error) {
	row := q.db.QueryRow(ctx, getLiveVerificationCode, arg.Channel, arg.Destination)
	var i VerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Destination,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementVerificationAttempts = `-- name: IncrementVerificationAttempts :one
UPDATE verification_codes
SET attempts = attempts + 1
WHERE id = $1
RETURNING attempts
`

func (q *Queries) IncrementVerificationAttempts(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementVerificationAttempts, id)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}
